-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Máy chủ: 127.0.0.1
-- Thời gian đã tạo: Th12 27, 2022 lúc 03:05 AM
-- Phiên bản máy phục vụ: 10.4.27-MariaDB
-- Phiên bản PHP: 8.1.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Cơ sở dữ liệu: `btl_ltw`
--

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `btl_san_pham`
--

CREATE TABLE `btl_san_pham` (
  `id_san_pham` int(20) NOT NULL,
  `ten_san_pham` varchar(50) NOT NULL,
  `so_luong` int(20) NOT NULL,
  `gia_tien` int(20) NOT NULL,
  `danh_muc_san_pham` varchar(50) NOT NULL,
  `mo_ta` text DEFAULT NULL,
  `anh_san_pham` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

--
-- Đang đổ dữ liệu cho bảng `btl_san_pham`
--

INSERT INTO `btl_san_pham` (`id_san_pham`, `ten_san_pham`, `so_luong`, `gia_tien`, `danh_muc_san_pham`, `mo_ta`, `anh_san_pham`) VALUES
(1, 'Mỳ rau củ ngũ vị ', 100, 60000, 'Mỳ', 'Mỳ được tráng và phơi theo phương pháp thủ công truyền thống, không làm công nghiệp. \n\nCơ sở làm mỳ là những nghệ nhân làm mỳ từ bé, đã mấy chục năm tuổi nghề ở đất Bắc Giang, yêu cầu sản phẩm của họ đạt ở mức độ hoàn hảo. \nChỉ cần ninh một chút sườn và với 1 vắt mì, cả nhà có bữa sáng ngon lành, đầy đủ dinh dưỡng. Ngoài ra nhúng lẩu, xào...cũng rất ngon luôn ạ\nThành phần: gạo, gấc, nghệ, chùm ngây, củ dền\n- Nguyên liệu Organic, không phẩm màu, không chất bảo quản và phụ gia\nThông tin dinh dưỡng/100Gr: \nCalories: 109\nCông dụng: \n\nGiúp giảm cân hiệu quả, hỗ trợ cho người đang ăn kiêng, tiểu đường, béo phì\n\nRất tốt với:\n\n- Phụ nữ muốn duy trì vóc dáng thon gọn/ chế độ ăn Eat Clean hạn chế tinh bột\n\n- Trẻ em/người lớn lười ăn rau táo bón.\n\n- Người có nhu cầu bồi bổ cơ thể\nHướng dẫn sử dụng:\n\nRửa qua nước sạch, cho vào nước sôi trong vòng 2-3 phút có thể sử dụng\nCách bảo quản:\nBảo quản nơi khô ráo, thoáng mát, tránh ánh nắng trực tiếp.\n\n', ''),
(2, 'Mỳ chũ rau củ lục vị ', 100, 65000, 'Mỳ', 'Mỳ được tráng và phơi theo phương pháp thủ công truyền thống, không làm công nghiệp. \r\n\r\nCơ sở làm mỳ là những nghệ nhân làm mỳ từ bé, đã mấy chục năm tuổi nghề ở đất Bắc Giang, yêu cầu sản phẩm của họ đạt ở mức độ hoàn hảo. \r\n\r\nChỉ cần ninh một chút sườn và với 1 vắt mì, cả nhà có bữa sáng ngon lành, đầy đủ dinh dưỡng. Ngoài ra nhúng lẩu, xào...cũng rất ngon luôn ạ\r\n\r\nThành phần: gồm: gạo, gấc, mè, nghệ, đậu biếc, khoai lang tím, củ dền đỏ, trắng, chùm ngây\r\n\r\n- Nguyên liệu Organic, không phẩm màu, không chất bảo quản và phụ gia\r\n\r\nThông tin dinh dưỡng/100Gr: Calories: 109\r\nCông dụng: \r\nGiúp giảm cân hiệu quả, hỗ trợ cho người đang ăn kiêng, tiểu đường, béo phì\r\nRất tốt với:\r\n- Phụ nữ muốn duy trì vóc dáng thon gọn/ chế độ ăn Eat Clean hạn chế tinh bột\r\n\r\n- Trẻ em/người lớn lười ăn rau táo bón.\r\n\r\n- Người có nhu cầu bồi bổ cơ thể\r\nHướng dẫn sử dụng:\r\nRửa qua nước sạch, cho vào nước sôi trong vòng 2-3 phút có thể sử dụng\r\nCách bảo quản:\r\nBảo quản nơi khô ráo, thoáng mát, tránh ánh nắng trực tiếp.\r\n\r\n', ''),
(3, 'Hạt Macca sấy 500g', 100, 180000, 'Hạt', 'CAM KẾT: HẠT MACCA SẤY MỚI MỖI TUẦN KHÔNG HÔI DẦU\r\n\r\n500g Hạt Macca nứt vỏ trồng theo quy trình hữu cơ chuẩn sạch tại Di Linh Lâm Đồng. Size A\r\n \r\n- CÓ TẶNG KÈM ĐỒ TÁCH VỎ\r\nHÀNG SẤY NỨT TỰ NHIÊN - ĐẢM BẢO CHUẨN QUY TRÌNH SẤY DINH DƯỠNG XUẤT KHẨU CHÂU ÂU GIÚP BẢO TOÀN HÀM LƯỢNG DINH DƯỠNG QUÝ GIÁ CỦA MACCA\r\nNỨT TỰ NHIÊN RẤT DỄ TÁCH - KHÔNG CÓ VỤN VỎ NHƯ HÀNG CƯA.\r\n\r\nNhà mình có vựa Macca xuất khẩu chuyên bán sỉ nay mình bán thêm trên Shopee bằng giá mình bán sỉ cho các mối để mọi người ăn thử.\r\n- Hạt to ngon và đều.\r\n- Hàng mới thơm ngon chứ không phải hôi dầu như Macca nước ngoài đâu nhé ạ.\r\n- Macca nhà mình sấy mới mỗi tuần không chất bảo quản cực kì an toàn.\r\n\r\n- Hạt macca còn có tên gọi khác là hạt macadamia, có xuất xứ từ Úc và ngày nay đã xuất hiện tại nhiều nơi trên thế giới và trong đó có tỉnh Lâm Đồng - Việt Nam. Hạt macca tươi có hương vị tinh tế, giống như bơ với vị thơm bùi, đem lại cảm giác mới lạ cho những người lần đầu được thưởng thức. Tương tự hầu hết các loại hạt khác, hạt mắc ca sấy lạnh rất giàu khoáng chất và dinh dưỡng có lợi cho sức khỏe. Do đó, đây là loại hạt dinh dưỡng mà ai cũng đều có thể sử dụng đặc biệt là Mẹ Bầu cần bổ sung dinh dưỡng để nuôi con.\r\n\r\nNgày nay, người tiêu dùng luôn mong muốn được sử dụng những thực phẩm sạch, tự nhiên để đảm bảo sức khỏe. vậy, Nông Sản Sạch  đã cho ra đời dòng sản phẩm hạt Mắc Ca Lâm Đồng nứt vỏ thơm ngon và đạt chuẩn.\r\n\r\nTại sao nên sử dụng sản phẩm hạt macca nứt vỏ của Nông Sản Sạch Việt Nam?\r\n- Chuyên cung cấp hạt mắc ca sạch, sản xuất trong môi trường khép kín từ khâu thu hoạch cho đến khâu sản xuất.\r\n- Tỉ lệ hạt macca đạt chất lượng cao.\r\n- Nguyên liệu đầu vào (hạt macca tươi) để chế biến hạt mắc ca sấy được trồng theo mô hình nông trại sạch, tuyệt đối không sử dụng thuốc Bảo vệ thực vật.\r\n- Cam kết đổi trả nếu không hài lòng\r\n- Sẵn sàng hỗ trợ, giải quyết mọi vấn đề của khách hàng Trước - Trong - Sau khi sử dụng sản phẩm\r\n\r\nCÁCH BẢO QUẢN\r\n- Bảo quản tại nơi thoáng mát, khô ráo, điều kiện bình thường, tránh ánh sáng trực tiếp. Hạn sử dụng 12 tháng kể từ ngày sản xuất.\r\n- Sau khi xé bao bì sản phẩm, nên đậy kín sản phẩm hoặc bỏ vào ngăn mát tủ lạnh. \r\n- Bảo quản tốt nhất ở nhiệt độ 8- 70 oC, độ ẩm dưới 55%.\r\nHạn sử dụng: 12 tháng kể từ ngày sản xuất ', ''),
(4, 'Hạt điều sấy 500g', 100, 99000, 'Hạt ', 'Sản phẩm chất lượng từ hạt điều rang muối, bơ Kim Thanh loại 1 đóng thùng 10kg\r\nSử dụng trực tiếp hoặc làm nguyên liệu sản xuất bánh trung thu thập cẩm\r\nBảo quản nơi khô ráo, thoáng mát\r\nXuất xứ: Việt Nam', ''),
(5, 'Hạt hạnh nhân sấy 500g ', 100, 205000, '', '- Khối lượng: 500gram/túi. Có cả 2 loại : hạnh nhân tươi và hạnh nhân rang\r\n\r\n- Xuât xứ: Mỹ\r\n\r\n- Hạn sử dụng: 1 NĂM . Hạnh nhân tươi thì phải bảo quản ngăn mát tủ lạnh để tránh hỏng, nếu hạnh nhân rang thì để nhiệt độ thường vẫn không sao nhé.\r\n\r\n-Tác dụng: các bạn dùng để làm sữa hạnh nhân uống để lợi sữa, kích thích sữa về, hoặc làm sữa cho bé uống, hầm thịt, hoặc ăn trực tiếp\r\n\r\n- Ghi chú:  tất cả các sản phẩm này đều có chứng nhận nhập khẩu Mỹ và ra giấy HỢP QUY theo luật nhà nước chứng nhận xuất xứ, Lê tuyệt đối không bán hàng Trung Quốc như một số bạn đang bán với giá siêu rẻ nha.\r\n\r\nHướng dẫn bảo quản:  ngăn mát tủ lạnh sẽ bảo quản được 4 tháng, ngăn đông tủ lạnh bảo quản được 1 năm, có thể để ở nhiệt độ phòng 7-10 ngày.', ''),
(6, 'Hạt óc chó sấy 500g', 100, 215000, 'Hạt ', '– Giao hàng: freeship tận nhà khi mua 1kg trở lên (không áp dụng ship gấp)\r\n \r\n– Khối lượng: 500gram/túi\r\n \r\n– Hạn sử dụng: 1 năm ạ. Ăn không hết thì để tủ lạnh ngăn mát, hạt sẽ giữ độ giòn mãi luôn ạ\r\n \r\n-Xuất xứ: Hồi ra nước ngoài, Lê có quen một anh bạn người Mỹ , anh ấy đã giới thiệu Lê về các loại hạt này. Anh ấy đã giúp Lê đưa nó về VN để giới thiệu với các bạn Việt ạ. (anh này cũng thường xuyên đến VN hằng năm vì yêu mến VN đó ạ)\r\n \r\n– Ghi chú: tất cả các sản phẩm này đều có chứng nhận nhập khẩu từ một công ty Hoa Kì, nên mọi người yên tâm. Cam kết đền tiền nếu phát hiện hàng có xuất xứ Trung Quốc.\r\n\r\n\r\n………………………………………………………………\r\n\r\n…………………………….\r\n ', ''),
(7, 'Túi mix 4 hạt bất kỳ (óc chó, hạnh nhân, điều, mac', 100, 350000, 'Hạt ', 'Mua 1 hộp nhưng được thưởng thức tới 5 loại hạt Các loại hạt được mix với tỉ lệ đều nhau, thích hợp cho khẩu phần ăn sáng với sữa chua và yến mạch. Đây là một lựa chọn thông minh khi bạn muốn sử dụng đa dạng các loại hạt và tăng cường dưỡng chất, chất xơ cho cơ thể. Bao gồm: Nhân hạt óc chó đỏ, Hạnh nhân, Macca, Hạt điều, Hạt bí xanh tách vỏ. Đóng gói trong hũ nhựa chắc chắn, date rất mới, nhập tới đâu bán tới đó. Bạn có biết việc bổ sung siêu thực phẩm hàng ngày là một xu hướng trên thế giới. Hãy là người tiêu dùng thông thái để bắt kịp xu hướng này. Đội ngũ Duti Sister trẻ đầy nhiệt huyết và có niềm đam mê với các loại siêu thực phẩm. Duti Sister  luôn mang lại giá trị hàng đầu cho bạn. Bằng việc bỏ qua nhà phân phối trung gian, Duti Sister  có thể cung cấp sản phẩm với giá cả phải chăng hơn.\r\nHạn sử dụng: 06 tháng ( Date luôn mới vì sản phẩm được nhập liên tục).\r\n\r\nHướng dẫn sử dụng: Ăn trực tiếp, dùng làm salad, tốt cho mẹ bầu.\r\n\r\nHướng dẫn bảo quản: Bảo quản tại nơi thoáng mát, khô ráo, điều kiện bình thường, tránh ánh sáng trực tiếp. Sau khi xé bao bì sản phẩm, nên đậy kín sản phẩm hoặc bỏ vào ngăn mát tủ lạnh. Trọng lượng: 500g', ''),
(8, 'Trà hoa cúc (Chrysanthemum tea) túi 500g ', 100, 99000, 'Trà ', '   SHOP MỚI RA THÊM MẪU MỚI TRÒN 20 VỊ CỐ ĐỊNH\r\nSẢN PHẨM DO SHOP TỰ CHẾ BIẾN CHỦ YẾU XUẤT SỈ NÊN ĐẢM BẢO HÀNG ĐỘC QUYỀN, HÀNG LUÔN MỚI BÓC KHUÔN KHÔNG QUÁ 5 NGÀY LÀ XUẤT.  \r\n Shop luôn đặt chữ Tâm và lợi ích khách hàng lên hàng đầu nên sản phẩm luôn luôn hoàn thiện hơn và đảm bảo an toàn sạch sẽ.\r\nKHÁCH SỈ INBOX ĐỂ ĐƯỢC GIÁ ƯU ĐÃI.\r\nRiêng trà gừng mẫu mới không có miếng gừng khô trên bề mặt nhưng viên trà vẫn thơm và có vị cay của gừng nhé bạn.\r\n   - Trà viên được ép từ những bông hoa tự nhiên được phơi hoặc sấy khô kết hợp với mật ong và đường phèn.\r\n   - Đây là sản phẩm truyền thống lâu đời và đặc trưng của vùng Vân Nam - Trung Quốc và shop sang học hỏi kinh nghiệm để tự nấu vì shop có người nhà là người Trung Quôc\'.\r\n   -  Mùa hông uống nóng ấm người, tăng sức đề kháng, mùa hè cho thêm đá giải nhiệt, giải khát.\r\n ? Công dụng: Những loại trà này đều rất tốt cho sức khỏe và  mỗi loại cho ta 1 công dụng khác nhau.\r\nCác bạn xem công dụng ở ảnh thứ 2 trên sản phẩm nhé\r\n  \r\n ? Cách dùng: Lấy 1 viên trà cho vào 180 - 200ml nước nóng chờ đường tan, hoa nở và thưởng thức.\r\n   Mùa hè có thể cho thêm đá  để giải nhiệt\r\n500g khoảng 25-30 viên.\r\n\r\nHSD: 3 tháng, nên bảo quản tủ mát\r\n', ''),
(9, 'Trà Gạo Lứt, Hoa Nhài, Cỏ Ngọt, Kỳ Tử, Táo Đỏ, Đậu', 100, 88000, 'Trà ', 'Trà Gạo Lứt, Hoa Nhài, Cỏ Ngọt, Kỳ Tử, Táo Đỏ, Đậu Đen, Đậu Đỏ, Lá Nếp Hộp 30 Túi Lọc - Siêu Thị Thiên Nhiên\r\n THÔNG TIN SẢN PHẨM:\r\n- Xuất xứ: Việt Nam\r\n\r\n- Khối lượng: 500gram\r\n\r\n- Ngày sản xuất: In trên bao bì\r\n\r\n- Hạn sử dụng: 12 tháng\r\n\r\n- Đạt chuẩn ISO 22000 - 2018 và HACCP 2003\r\n\r\n- Check mã vạch trực tiếp trên bao bì của sản phẩm\r\nCÔNG DỤNG:\r\n\r\n -  Trà gạo lứt Siêu Thị Thiên Nhiên giúp cải thiện làn da, mái tóc và vóc dáng\r\n\r\n - Thanh nhiệt, thải độc gan\r\n\r\n - Tốt cho phụ nữ bầu và sau khi sinh\r\n\r\n - Giảm cholesterol xấu\r\n\r\n - Trà gạo lứt tăng cường chức năng của thận, người lớn sẽ không bị tiểu đêm.\r\n\r\nĐỐI TƯỢNG SỬ DỤNG:\r\n\r\n- Người muốn duy trì vóc dáng\r\n\r\n- Người uống nhiều rượu bia\r\n\r\n- Người muốn giải nhiệt, thanh lọc gan, cải thiện chức năng gan, thận.\r\n\r\n- Dân văn phòng ngồi nhiều, ít vận động, muốn duy trì vóc dáng.\r\n\r\n- Những người bị bệnh gout và phong thấp.\r\n\r\n- Người bị tiểu đường, mỡ máu, cao huyết áp.\r\n\r\n- Người lớn tuổi thường xuyên bị tiểu đêm, mất ngủ.\r\n\r\n- Đặc biệt, rất tốt cho mẹ bầu và mẹ sau sinh.\r\nHƯỚNG DẪN SỬ DỤNG:\r\n\r\n- Cho 1 túi trà vào 500ml nước nóng trên 85 độ ngâm 5-10 phút là có thể sử dụng\r\n\r\n- Có thể cho thêm đá nếu bạn thích uống lạnh. Dùng thay nước lọc uống hàng ngày.\r\n\r\n- Trà sau khi pha bạn nên sử dụng trong vòng một ngày, không nên để qua ngày \r\nBẢO QUẢN:\r\n\r\n- Nơi khô ráo thoáng mát, tránh ánh nắng mặt trời\r\n\r\n- Đóng kín sau khi sử dụng\r\n CAM KẾT CỦA SHOP:\r\n\r\n- Sản phẩm chính hãng 100%\r\n\r\n- 100% từ thiên nhiên không hương liệu, không chất bảo quản.\r\n\r\n- Đổi trả miễn phí nếu do lỗi của shop\r\n\r\n- Hàng luôn sẵn, giao ngay khi có đơn\r\n\r\nCHÚ Ý: Sản phẩm này không phải là thuốc và không có tác dụng thay thế thuốc chữa bệnh\r\n', ''),
(10, 'Trà hoa cúc gạo lứt thanh nhiệt, ngủ ngon, điều ho', 100, 70000, 'Trà', 'TRÀ HOA CÚC GẠO LỨT THANH NHIỆT, NGỦ NGON, ĐIỀU HOÀ HUYẾT ÁP - TRÀ HOA CÚC GẠO LỨT \r\n\r\nTÁC DỤNG TRÀ HOA CÚC GẠO LỨT \r\n- Trà gạo lứt hoa cúc thanh nhiệt, giải độc, mát gan, giúp ăn ngon ngủ ngon, da dẻ hồng hào tươi sáng.\r\n- Trà gạo lứt hoa cúc tăng cường hệ miễn dịch, sức đề kháng của cơ thể, ngừa cảm lạnh.\r\n- Trà gạo lứt hoa cúc hỗ trợ ngăn ngừa huyết áp cao, tiểu đường, máu nhiễm mỡ, thấp khớp, gout...\r\n- Đặc biệt, trà gạo lứt hoa cúc Quê Việt hỗ trợ  thon gọn vóc dáng.\r\n\r\nCÁCH DÙNG TRÀ HOA CÚC GẠO LỨT \r\n- Cho 1 túi vào 1,5 lít nước đun sôi 1 phút, hoặc ngâm từ 10 - 15 phút trong nước nóng trên 80 độ CC, trà sau khi đun bạn nên sử dụng trong vòng 1 ngày, có thể cho thêm đá nếu thích uống lạnh.\r\n- Bảo quản: Để nơi khô ráo, thoáng mát.\r\n\r\nTHÔNG TIN SẢN PHẨM TRÀ HOA CÚC GẠO LỨT\r\n- Sản phẩm: Trà hoa cúc gạo lứt \r\n- Thương hiệu: Beautiful Health\r\n- Xuất xứ: Việt Nam\r\n- Dạng bào chế: Túi trà \r\n- Thành phần: Gạo lứt, đậu đen xanh lòng, đậu đỏ, kỷ tử, hoa cúc, xạ đen\r\n-  Hạn sử dụng: 2 năm kể từ ngày sản xuất (xem trên bao bì)\r\n- Phân phối : GOOD DAY STORE', ''),
(11, 'Granola siêu hạt ăn kiêng thêm hạt Macca 500g ', 100, 189000, 'Granola', 'Granola siêu hạt ăn kiêng ngũ cốc giảm cân dinh dưỡng eat clean không đường thêm hạt Macca ít yến mạch từ Nông Sản Sạch Giọt Nắng.\r\n\r\nVới mong muốn đem lại lại thân hình khỏe đẹp, thon gọn và săn chắc, Giọt Nắng xin giới thiệu siêu phẩm Granola siêu hạt ăn kiêng dinh dưỡng, hỗ trợ giảm cân tự nhiên, đảm bảo an toàn cho sức khỏe với nguyên liệu đầu vào và quy trình sản xuất đã được kiểm nghiệm và cấp chứng chỉ An Toàn VSTP.\r\n\r\nGranola siêu hạt ăn kiêng không đường được mix từ 10 loại Hạt và Quả nguyên vị, yến mạch nhập khẩu từ Úc được nướng cùng mật ong hoa cà phê của núi rừng Tây Nguyên, đem đến vị thơm ngon, giòn rụm mà lại vô cùng dinh dưỡng.\r\n\r\nVề hương vị, ngũ cốc giảm cân granola siêu hạt có vị truyền thống và vị socola rất thơm ngon\r\n\r\nNgũ cốc giảm cân granola không đường được mix 10 loại Hạt & Quả:\r\n (1) Hạt Macca giàu dinh dưỡng (Chỉ có trong phân loại siêu hạt)\r\n (2) Hạt óc chó\r\n (3) Hạt bí xanh\r\n (4) Hạt Điều\r\n (5) Hạt hạnh nhân\r\n (6) Nho vàng\r\n (7) Nho nâu\r\n (8) Xoài sẩy dẻo\r\n (9) Dừa sấy thơm giòn\r\n (10) Yến mạch Úc sấy mật ong giòn rụm, có thêm vị socola để thơm ngon hơn\r\n\r\n * Công dụng của granola siêu hạt ăn kiêng\r\n - Hỗ trợ giảm cân hiệu quả\r\n - Chống oxi hóa, trẻ đẹp làn da\r\n - Bổ sung hàm lượng Omega 3, chất xơ cao\r\n - Giàu Vitamin & khoáng chất\r\n - Granola Yến Mạch không đường giúp Cung cấp năng lượng dồi dào, thực đơn keto, ăn kiêng eat clean hoàn hảo\r\n * Đối với Mẹ bầu:\r\n - Hỗ trợ phát triển não bộ, mắt và hệ miễn dịch cho trẻ\r\n - Cung cấp năng lượng, dinh dưỡng lành mạnh cho mẹ\r\n - Cải thiện dinh dưỡng, ổn định huyết áp\r\n * Sử dụng hạt Granola giảm cân hàng ngày vào bữa sáng & bữa phụ, mỗi bữa chỉ với 2 muỗng granola yến mạch không đường tương đương 30g ~ 100 calo vừa giúp bạn có những bữa ăn kiêng ngon miệng, giàu dinh dưỡng và đặc biệt hơn là giúp săn chắc, mịn màng làn da và hỗ trợ giảm cân, tăng cơ giảm mỡ rất hiệu quả.\r\n * Tip: Ngoài sử dụng trực tiếp, bạn có thể mix ngũ cốc giảm cân granola vị truyền thống hoặc vị socola cùng sữa chua không đường, sữa tươi & hoa quả, hương vị đa dạng và rất thơm ngon.\r\n\r\n - Thông tin bổ sung\r\n * Hạn sử dụng: 6 Tháng\r\n (Nên sử dụng trong 20 ngày từ khi mở nắp sản phẩm trải nghiệm hương vị tốt nhất)\r\n Tại sao nên sử dụng sản phẩm Granola siêu hạt ăn kiêng của Nông Sản Sạch Giọt Nắng?\r\n * Giọt Nắng xin CAM KẾT:\r\n - Hoàn toàn không đường, không chất béo xấu, eat clean\r\n - Không sử dụng các chất tạo hương, tạo màu và không chất bảo quản\r\n - Miễn phí đổi hàng mới trong 15 ngày nếu không hài lòng.\r\n - Sẵn sàng hỗ trợ, giải quyết mọi vấn đề của khách hàng Trước – Trong và Sau khi sử dụng sản phẩm.\r\n - Luôn ưu tiên sản xuất sản phẩm mới nhất đến tay khách hàng.\r\n - Chuyên cung cấp các sản phẩm sạch, thuận tự nhiên và tốt cho sức khỏe\r\n', ''),
(12, 'Granola Siêu Hạt Vị Vani 500g', 100, 253000, 'Granola', 'inh dầu Vani nguyên chất thơm dịu, nhẹ nhàng, tôn lên hương vị tự nhiên nguyên bản của từng loại hạt/quả. Rất dễ dàng khi chế biến hay kết hợp cùng những nguyên liệu khác cho bữa ăn Granola thêm đa dạng\r\n\r\n 100% tự nhiên nguyên chất:\r\n\r\nKhông sử dụng đường tinh luyện\r\nKhông chất bảo quản/ phụ gia \r\nKhông chứa chất biến đổi Gen \r\nKhông màu thực phẩm\r\nCó 0% Chất béo chuyển hóa\r\n Công nghệ nướng – sấy hiện đại: duy trì được sự thơm ngon, giòn ngậy và ngọt tự nhiên của loại hạt.\r\n\r\n Phù hợp cho bữa sáng, bữa xế, bữa trưa tiện lợi cho mọi đối tượng sử dụng.\r\n\r\nKhối lượng: 500gr\r\nThương hiệu: Anpaso\r\nDòng sản phẩm: Ngũ cốc dinh dưỡng Granola\r\nXuất xứ: Việt Nam\r\nVị: Vani', ''),
(13, 'Granola siêu hạt vị matcha 500g ', 100, 316000, 'Granola', 'Tên sản phẩm: Granola Siêu Hạt Vị Matcha Anpaso 500g \r\nThương hiệu: Anpaso \r\nXuất xứ: Việt Nam \r\nThành phần: Yến mạch 35%, Mật ong, Hạt điều, Hạnh nhân, Hướng dương, Bí xanh, Óc chó, Nho khô, Nam việt quất, Xoài sấy dẻo, Mơ sấy dẻo, Bột Matcha \r\nCông dụng: \r\nGiúp giữ gìn vóc dáng cơ thể: Trong Granola có nhiều thành phần được mệnh danh là thuần chay như: Các loại hạt, trái cây khô, yến mạch,… Nhưng nó lại giúp cung cấp đủ năng lượng cho cơ thể, hàm lượng protein cao vì vậy nó đặc biệt thích hợp với những người ăn kiêng, giảm cân và ăn chay. \r\nTốt cho hệ tiêu hóa: Trong 100 gram granola thì chứa 5g chất xơ. Nhờ hàm lượng chất xơ dồi dào mà hệ tiêu hóa của bạn hoạt động tốt hơn ngừa được bệnh đường ruột như: táo bón, rối loạn tiêu hóa và đồng thời tránh cảm giác thèm ăn. Ngoài ra có thể hỗ trợ giảm lượng đường và cholesterol trong máu. \r\nTốt cho sức khỏe tim mạch: Trong 100 gram Granola thường chứa 12g chất béo không bão hòa đa, 4.4g chất béo không bão hòa đơn những chất béo này giúp bảo vệ tim mạch, ổn định huyết áp, giảm cholesterol trong máu, ngăn ngừa nguy cơ mắc bệnh tim. \r\nGranola bổ sung khoáng chất và vitamin: Thành phần chủ yếu trong Granola là: Yến mạch, các loại ngũ cốc, các loại hạt và các loại dầu như olive, dầu mè… Những loại hạt này giúp bổ sung cho cơ thể các khoáng chất cần thiết như: Magie, mangan, phốt pho, kẽm, đồng… ngoài ra cung cấp một lượng vitamin E dồi dào giúp cơ thể chống lão hóa. \r\nĐối tượng sử dụng: Chay, mặn đều dùng được. \r\nCách dùng: Dùng trực tiếp, hoặc ăn cùng sữa tươi/sữa chua/sinh tố/hoa quả/… \r\nQuy cách: 500g \r\nNSX & HSD: 12 tháng kể từ ngày sản xuất ', ''),
(14, 'Ngũ Cốc Granola Siêu Hạt Hương Vị Sô cô la – Hộp 5', 100, 129000, 'Granola', 'NGŨ CỐC GRANOLA SIÊU HẠT DINH DƯỠNG \r\n– Được mix từ các loại Hạt  dinh dưỡng và quả khô nhập khẩu, nướng  giòn cùng yến mạch Úc & tạo ngọt tự nhiên từ mật ong hoa cà phê, đem đến vị thơm ngon, giòn rụm,\r\n– Phù hợp cho tất cả mọi người, đặc biệt là người muốn giảm cân khoa học, eat clean, ăn uống lành mạnh\r\n– Được chọn lọc từ các nguyên liệu tự nhiên rõ ràng về nguồn gốc xuất xứ\r\n– Có  4 hương vị thơm ngon để thực khách lựa chọn: VỊ truyền thống – Chocolate  – Matcha  và đặc biệt là vị Phô mai Cheddar mới lạ.\r\n Thông tin chung\r\nXuất xứ: Việt Nam\r\nĐạt tiêu chuẩn Vệ sinh an toàn thực phẩm\r\nSố công bố:\r\nQuy cách đóng gói: Hộp 500g/ Hộp 250g/ Túi 100g\r\nThành phần: hạnh nhân Mỹ, óc chó vàng Chile, macca Đak Lak, Hạt điều Bình Phuớc, Bí xanh, Yến mạch Úc nguyên cám, nho khô Ấn Độ. hoa quả khô theo mùa (nam việt quất, dừa sấy khô nguyên vị, chanh dây sấy dẻo, hồng táo giòn, dâu tây…)\r\nNgày sản xuất: in trên bao bì\r\nHạn sử dụng: 6 tháng kể từ ngày sản xuất\r\nBảo quản: Bảo quản trong điều kiện mát và khô, bảo quản tốt nhất ở ngăn mát tủ lạnh, nhiệt độ 2-4 độ C\r\nSản phẩm không phù hợp với người bị dị ứng với các thành phần cuả sản phẩm.\r\n\r\n Tác dụng granola:\r\n– Không chứa chất béo xấu, không gây ảnh hưởng đến tim mạch\r\n– Giàu chất xơ và protein giúp giữ dáng, giảm cân, tăng cơ hiệu quả\r\n– Tốt cho cả mẹ bầu, trẻ em\r\nHướng dẫn sử dụng\r\n– Dùng ngay khi mở hộp để đảm bảo chất lượng hoàn hảo của bánh\r\n– Kết hợp với sữa chua, sinh tố rất ngon\r\n– Ăn từ 30-50gr / lần\r\n– Ăn vào bữa sáng, bữa phụ hoặc trước khi tập luyện để đạt hiệu quả tốt nhất.\r\n\r\nCAM KẾT:\r\n– Sản phẩm: Cam kết hàng chính hãng 100%\r\n– Tư vấn nhiệt tình, chu đáo luôn lắng nghe khách hàng để phục vụ tốt.\r\n– Chính sách đổi trả linh hoạt nếu hàng lỗi, sai mẫu\r\n– Giao hàng nhanh đúng tiến độ\r\n', ''),
(15, 'Combo 3 vị granola: siêu hạt, matcha, chocolate 20', 100, 300000, 'Granola', ' Ngũ cốc dinh dưỡng dành cho người muốn: giảm cân, điều chỉnh chế độ ăn và vóc dáng, mẹ bầu trong và sau sinh, trẻ nhỏ.\r\n\r\nMọi lứa tuổi đều có thể thêm Granola Siêu Hạt của OHOO! vào bữa ăn hàng ngày.\r\n Chỉ với 3  phút bạn đã có bữa ăn sáng thông minh, dinh dưỡng.\r\n\r\n \r\n\r\nSản phẩm Granola Siêu Hạt Nhà OHOO!: \r\n\r\n- Tỉ lệ hạt và quả: 80%\r\n\r\n- 12 thành phần: Yến mạch Úc sấy giòn, Hạt Macca, Hạt Óc chó đỏ,  Hạt Óc chó vàng,  Hạt Hạnh nhân, Hạt Điều sữa, Hạt Bí xanh, Nho khô vàng Ấn Độ, Nho khô đen Chile, Dâu Thái, Dừa sấy, Xoài sấy.\r\n\r\n- 3 vị: Mật ong, Matcha, Socola\r\n\r\n- 3 Không : chất bảo quản, đường hóa học, phụ gia\r\n\r\n \r\n Công dụng:\r\n\r\n- Thay thế bữa ăn chính trong ngày chỉ với 3 phút chuẩn bị\r\n\r\n- Thực phẩm chay, không đường\r\n\r\n- Hỗ trợ giảm cân, tăng cơ hiệu quả\r\n\r\n- Bổ sung protein, Vitamin, chất béo tốt, Omega-3 và chất sơ\r\n\r\n- Cung cấp chất chống oxy hóa để cơ thể trẻ hóa, tốt cho da và tóc\r\n\r\n- Ăn kiêng không thiếu chất, mệt mỏi\r\n\r\n  Đối tượng sử dụng:\r\n\r\n- Người tập thể hình\r\n\r\n- Mẹ bầu, trẻ nhỏ\r\n\r\n- Người ăn chay\r\n\r\n- Người ăn kiêng, giảm cân\r\n\r\n- Dân văn phòng, sinh viên bận rộn mà vẫn muốn có chế độ ăn healthy và ổn định vóc dáng\r\n\r\n \r\nSử dụng:\r\n\r\n- Sử dụng vào bữa sáng, bữa phụ\r\n\r\n- Ăn liền hoặc kết hợp với sữa chua và hoa quả tươi\r\n\r\n- Mỗi phần ăn 30-40g granola (2 thìa ăn cơm) xấp xỉ 130 calories\r\n Bảo quản:\r\n\r\n- HSD: 8 tháng kể từ ngày sản xuất và 4 tuần kể từ khi bóc sản phẩm', ''),
(16, 'Combo 2 trà hoa cúc 500g', 100, 120000, 'Trà', 'Combo quà tặng ý nghĩa đến từ Beautiful Health\r\nCombo 2 Lọ trà hoa  Cúc (Loại 1 thơm ngon - làm quà)\r\n\r\nDung tích 1 lọ/ 500g\r\n\r\n♻️ CÔNG DỤNG TRÀ HOA CÚC TRẮNG\r\n? Trà hoa cúc giúp ngăn ngừa chứng cao huyết áp, xoa dịu các cơn đau\r\n? Trà hoa cúc có tác dụng trẻ hóa làn da nhờ tinh chất thảo mộc, ngăn ngừa mụn phát triển, loại bỏ mỡ thừa giúp chị em giảm cân hiệu quả, giải tỏa căng thẳng, mệt mỏi, giãn cơ, khắc phục chứng mất ngủ. \r\n? Trà hoa cúc đồng thời kháng khuẩn, ức chế sự phát triển của các loại nấm ngoài da, ngăn ngừa tóc gãy rụng, giảm đau đầu, phong thấp.\r\n? Khi uống trà hoa cúc khô thường xuyên còn giúp chống lại sự tăng đường huyết - một trong những dấu hiệu của bệnh tiểu đường\r\n\r\n♻️ CÔNG DỤNG TRÀ HOA CÚC VÀNG\r\n1. Cải thiện sức khỏe tim mạch\r\n2. Giải cảm\r\n3. Làm dịu mẩn đỏ do nóng trong\r\n4. Cải thiện sức khỏe đôi mắt\r\n5. Ngăn ngừa ung thư\r\n--- Cách sử dụng: Bạn có thể lấy từ 12-15g hoa hồng, hãm với nước sôi sau đó rót ra tách để thưởng thức. Hoặc bạn cũng có thể kết hợp hoa hồng với các loại trà khác để có hương vị thơm ngon hơn.\r\nLưu ý: Không dùng cho phụ nữ có thai, sẽ làm tăng co bóp tử cung gây nguy cơ sẩy thai\r\n\r\n--- Bảo quản: bảo quản nơi khô ráo thoáng mát, tránh độ ẩm\r\n\r\nHạn sử dụng: 12 tháng kể từ khi mở nắp', ''),
(17, 'Combo 2 Granola matcha-chocolate 500g ', 100, 500000, 'G', NULL, '');

--
-- Chỉ mục cho các bảng đã đổ
--

--
-- Chỉ mục cho bảng `btl_san_pham`
--
ALTER TABLE `btl_san_pham`
  ADD PRIMARY KEY (`id_san_pham`);

--
-- AUTO_INCREMENT cho các bảng đã đổ
--

--
-- AUTO_INCREMENT cho bảng `btl_san_pham`
--
ALTER TABLE `btl_san_pham`
  MODIFY `id_san_pham` int(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=18;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
