-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jan 07, 2023 at 03:29 PM
-- Server version: 10.4.25-MariaDB
-- PHP Version: 8.1.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `beautiful-health`
--

-- --------------------------------------------------------

--
-- Table structure for table `tbl_san_pham`
--

CREATE TABLE `tbl_san_pham` (
  `sp_id` int(11) NOT NULL,
  `sp_ten` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `sp_so_luong` int(10) NOT NULL,
  `sp_don_vi` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `sp_gia_tien` int(20) NOT NULL,
  `lsp_id` int(11) NOT NULL,
  `sp_mo_ta` varchar(5000) COLLATE utf8_unicode_ci NOT NULL,
  `sp_anh` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `sp_anh2` varchar(200) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `tbl_san_pham`
--

INSERT INTO `tbl_san_pham` (`sp_id`, `sp_ten`, `sp_so_luong`, `sp_don_vi`, `sp_gia_tien`, `lsp_id`, `sp_mo_ta`, `sp_anh`, `sp_anh2`) VALUES
(1, 'Hạt macca sấy', 60, 'Hộp', 300000, 1, 'Hạt macca nứt vỏ TANU NUTS, hạt mắc ca Tây Nguyên đã rang sấy tốt cho bà bầu\r\n- Thông tin sản phẩm:\r\n▪️ Trọng lượng: Gói 500gr hút chân không hoặc hũ nhựa 450gr\r\n▪️ Xuất xứ: Lâm Đồng, Việt Nam\r\n▪️ Hạn sử dụng: 6 tháng kể từ ngày sản xuất (in trên bao bì)\r\n▪️ Phân phối bởi công ty TNHH Hạt dinh dưỡng Tây Nguyên\r\n- Đặc điểm nổi bật của sản phẩm:\r\n- Nguồn nguyên liệu 100% hạt macca sạch, nguyên liệu từ vùng đất Tây Nguyên màu mỡ.\r\n- Quy trình sản xuất đạt chuẩn VSATTP. \r\n- Không có chất bảo quản, an toàn cho sức khỏe.\r\n\r\n- Kỹ thuật sấy nứt theo công nghệ cao cho đầu ra hạt macca chất lượng, đạt độ ẩm tiêu chuẩn, dễ tách vỏ hạt.\r\n- Hạt macca được xử lý bảo quản lạnh kỹ lưỡng trong môi trường chân không, chống nấm mốc.\r\n- Shop cam kết bán hàng chính hãng. Đổi trả trong vòng 15 ngày nếu phát hiện lỗi từ nhà sản xuất.\r\n- Thành phần dinh dưỡng và công dụng:\r\n- Với 718 calo/100gr hạt mắc ca là loại hạt có giá trị calo cao nhất trong các loại hạt dinh dưỡng.\r\n- 21% vitamin B6, 100% thiamin, và 12% riboflavin.\r\n- Là nguồn cung cấp dồi dào các khoáng chất quan trọng cho cơ thể như: canxi, kẽm, mazê, sắt…\r\n- Mẹ bầu sử dụng hạt macca Tây Nguyên sẽ rất tốt cho sức khỏe và em bé sẽ được cung cấp dinh dưỡng tốt nhất cho sự phát triển trí não.\r\n- Cung cấp nguồn năng lượng dồi dào, chống các bệnh liên quan đến tim mạch, ngăn ngừa ung thư, có tác dụng đẹp da, hỗ trợ trao đổi chất và chống oxy hóa.\r\n- Hướng dẫn sử dụng: \r\n- Mỗi ngày bạn nên sử dụng 4-5 hạt macca sẽ cung cấp cho cơ thể hàm lượng calo cần thiết, giúp làm chậm quá trình lão hóa, giúp da trắng hồng. \r\n- Nhân hạt mắc ca có thể ăn liền hoặc sử dụng làm bánh, nếu bạn sử dụng để nấu cháo hoặc xay sữa cho bé sẽ giúp bé phát triển trí não rất tốt.\r\n- Hạt macca đã được sấy chín nên bạn có thể ăn liền hoặc có thể cho vào lò vi sóng nướng nhẹ thì mắc ca sẽ giòn và thơm hơn. \r\n- Bảo quản: Bảo quản hạt macca tại nơi thoáng mát, khô ráo, điều kiện bình thường, tránh ánh sáng trực tiếp. Sau khi xé bao bì sản phẩm, nên đậy kín sản phẩm hoặc bỏ vào ngăn mát tủ lạnh. \r\n', 'sp1.png', 'macca1.jpg'),
(2, 'Hạt óc chó sấy', 60, 'Hộp', 250000, 1, 'Nhân óc chó vàng TANU NUTS, hạt óc chó tách vỏ Chile tốt cho bà bầu, cho bé\r\n- Thông tin sản phẩm:\r\n▪️ Trọng lượng: Gói/ hũ nhựa 400gr hút chân không hoặc hũ nhựa 200gr\r\n▪️ Xuất xứ: Nhập khẩu Chile\r\n▪️ Hạn sử dụng: 6 tháng kể từ ngày sản xuất (in trên bao bì)\r\n▪️ Phân phối bởi công ty TNHH Hạt dinh dưỡng Tây Nguyên\r\n+ Đặc điểm nổi bật của sản phẩm:\r\n- Nguồn nguyên liệu hạt óc chó nhập khẩu, hạt vụ mới.\r\n- Quy trình đóng gói tách vỏ hạt, đóng gói tại Việt Nam đạt chuẩn VSATTP.\r\n- Hạt óc chó không có chất bảo quản, không chất tẩy trắng, không hun trùng, không tẩm ướp, an toàn cho sức khỏe.\r\n- Quy trình chế biến đảm bảo theo Tiêu chuẩn vệ sinh An toàn thực phẩm.\r\n- Bảo quản lạnh kỹ lưỡng trong môi trường chân không, chống nấm mốc.\r\n- Shop cam kết bán hàng chính hãng. Đổi trả trong vòng 15 ngày nếu phát hiện lỗi từ nhà sản xuất.\r\n+ Thành phần dinh dưỡng và công dụng:\r\n- Hạt óc chó bổ sung vitamin B1, B2, A,E, Protein,... và khoáng chất cho cơ thể như canxi, phốt pho, mangan, sắt, đồng,…\r\n- Axit béo Omega 3 có trong quả óc chó (cao gấp 5 lần cá hồi) nên giúp duy trì chất béo cấu trúc loại chất chiếm đến 60% bộ não nên đặc biệt rất tốt cho mẹ mang thai và trẻ em.\r\n- Chứa nhiều chất tốt cho phụ nữ mang thai và trẻ nhỏ.\r\n- Cải thiện giấc ngủ, cải thiện trí nhớ.\r\n- Giảm Cholesterol xấu, điều hòa huyết áp, ngăn ngừa bệnh tim mạch, giảm nguy cơ mắc bệnh ung thư.\r\n- Tốt cho bệnh nhân bị tiểu đường.\r\n- Giúp cho các chị em cải thiện vòng một, giảm cân, làm đẹp da và tóc.\r\n\r\n+ Hướng dẫn sử dụng: \r\n- Mẹ bầu có thể ăn óc chó bất cứ khi nào mà mình thích.\r\n- Tốt nhất nên ăn vào buổi sáng và buổi trưa.\r\n- Mỗi ngày bạn chỉ nên sử dụng 6 đến 8 quả óc chó.\r\n- Lúc đầu, khi mới ăn, bạn chỉ nên sử dụng 1-2 quả cho quen dần sau đó mới tăng đến lượng như trên.\r\n- Nên sử dụng cả lớp da vỏ mỏng của quả óc chó không nên bỏ đi, lớp này có chứa rất nhiều dưỡng chất cần thiết cho thai kỳ.\r\n- Hạt óc chó có chứa nhiều dầu nên rất nhanh hỏng nếu không được bảo quản cẩn thận.\r\n- Nên duy trì thường xuyên trong quá trình mang thai để có được hiệu quả tốt nhất.\r\n- Bạn nên nhai kỹ, ăn từ từ để cảm nhận vị bùi, ngọt của nhân hạt óc chó cũng như giúp cơ thể hấp thu tốt hơn.', 'sp2.png', 'occho1.jpg'),
(3, 'Hạt Hạnh Nhân Sấy Mộc  ', 60, 'Hộp', 300000, 1, 'MÔ TẢ SẢN PHẨM\r\n\r\n   - Hạnh nhân sấy mộc nhập khẩu từ Mỹ và Úc, giòn, thơm, béo , ít cabs và giàu chất béo , protein , chất xơ lành mạnh, giúp làm giảm cholesterol nên có thể hỗ trợ quá trình giảm cân.\r\n   - Kích thước             : 25/27 hạt to, rất phù hợp để dùng trực tiếp, xay sữa hoặc làm granola cao cấp.\r\n   - Quy cách đóng gói : Hũ nhựa 500gr và 350gr\r\n\r\nHạnh nhân của shop luôn mới, giòn rụm, không chất bảo quản, đặc biệt nguồn gốc hàng nhập rõ ràng, không trôi nổi nên chất lượng yên tâm cho bạn nào tìm kiếm nguồn hạt để ăn dinh dưỡng, ăn kiêng , eatclean nhé.\r\n\r\nShop luôn kiểm tra, phân loại trước khi gửi đến khách hàng. Bao đổi trả sản phẩm trong vòng 7 ngày nếu hàng hóa không như miêu tả nè.\r\n\r\nSỉ từ 5kg lộn xộn, giá bằng giá xưởng nha, hàng luôn sẵn ở kho HCM, giảm bớt phí vận chuyển cho mọi người trong thời kỳ bão giá nè . \r\n\r\nZalo /Phone : 0902.931.924 hoặc 0977.933.947 \r\n\r\nChúc mọi người có 365 Ngày sống vui khỏe nhé', 'hat3.png', 'hanhnhan.jpg'),
(4, 'Hạt điều rang', 60, 'Hộp', 300000, 1, '1. HẠT ĐIỀU RANG KHÔNG MUỐI\r\n- Được nhập nguyên liệu từ hạt điều thuần chủng tại miền đất đỏ ( Bình Phước )\r\n- Đảm bảo mang đến hương vị đặc chưng nhất của hạt điều.\r\n- Hương vị béo đặng trưng và thơm nồng khi được nung trên lữa sẽ khiến bạn khó lòng quên được.\r\n\r\n2. LỢI ÍCH CỦA ĐIỀU SẤY MỘC ĐỐI VỚI SỨC KHỎE\r\n- Rất tốt cho mẹ bầu - phát triển trí não thai nhi\r\n- Cải thiện trí nhớ, cải thiện giấc ngủ ngon hơn\r\n- Tốt cho bệnh nhân bị tiểu đường, cao huyết áp, người bệnh ăn kiêng\r\n- Phòng chống bệnh ung thư hiệu quả\r\n- Ngăn ngừa bệnh tim mạch, củng cố động mạch. Hạn chế Cholesterol xấu.\r\n- Bổ sung chất xơ Giúp nhuận tràng\r\n- Cung cấp canxi, khoáng chất, Vitamin, Omega3 giúp Bảo vệ xương, chống lão hóa...\r\n- Giảm cân, làm đẹp da , tóc , giữ dáng cho người tập gym\r\n\r\n3. CÁCH SỬ DỤNG\r\n- Ăn trực tiếp như một loại snack mà không cần nấu.\r\n\r\n4. CÁCH BẢO QUẢN\r\n- Đóng kín sau khi sử dụng.\r\n- Để nơi thoáng mát, tránh hơi ẩm và ánh nắng mặt trời.\r\n- Để tủ lạnh nếu muốn bảo quản lâu hơn.', 'hat8.png', 'hatdieu.jpg'),
(5, 'Mỳ Chũ Rau Củ 4 Vị ', 100, 'Túi', 80000, 2, '1.Thông tin sản phẩm mì chũ rau củ:\r\nPhân loại	: Mỳ Chũ loại đặc biệt: có độ giòn, dẻo, dai và thơm ngon\r\nĐóng gói:	1kg/ gói\r\nThành phần: được làm từ những hạt gạo bao thai hồng nguyên chất, chùm ngây, đậu biếc, củ dền, cà rốt, đậu đỏ.\r\nHạn sử dụng: 12 tháng kể từ ngày sản xuất\r\nCách sử dụng: Được sử dụng chế biến các món ăn: nhúng lẩu, mỳ xào giòn, mỳ bò, mỳ hải sản...\r\nHướng dẫn bảo quản: Nơi thoáng mát, tránh ánh nắng trực tiếp, giữ bao bì luôn được kín\r\n\r\n2. Mì chũ rau củ đặc sản Bắc Giang cam kết:\r\nKHÔNG chứa chất bảo quản\r\nKHÔNG chất tạo màu\r\nKHÔNG chất tạo dai\r\nKHÔNG chiên qau dầu\r\n\r\n3. ORGAFOOD CAM KẾT HOÀN TIỀN 100% NẾU KHÔNG CHẤT LƯỢNG\r\n               -------\r\nORGAFOOD - UY TÍN - CHẤT LƯỢNG HÀNG ĐẦU\r\n               ------', 'mi4.png', 'mi4.jpg'),
(6, 'Mỳ Chũ Rau Củ 6 Vị', 100, 'Túi', 100000, 2, 'Nói đến mỳ chũ, chắc chắn nhiều người sẽ không còn xa lạ. Vì nó góp một phần vào bữa ăn của mỗi gia đình Việt. Trong đó, loại mỳ được đánh giá chất lượng ngon, có độ dai và được nhiều người thích nhất là mỳ chũ Lục Ngạn. Đây là loại mỳ nổi tiếng, chính hiệu được người Bắc Giang tự tay sản xuất ra. Để tạo ra những sợi mỳ vừa dai,vừa ngọt bùi, người làng nghề phải tiến hành rất nhiều công đoạn rất công phu. Sợi mỳ dai ngon và ngọt bùi có thể dùng làm phở, hủ tiếu, phở xào hoặc nhúng để ăn lẩu… sợi mì không bị nát! Mỳ chũ nhà làm trực tiếp nên mọi người yên tâm về chất lượng nhé. Sợi mì trắng đục chứ không trắng trong như hàng ngoài chợ bán!\r\nMỳ dành cho người ăn kiêng, giảm béo, ăn theo chế độ healthy ko tinh bột xấu\r\n\r\nMỳ chũ có thể kết hợp với nhiều nguyên liệu như xào thịt bò, xào cần tây, xào măng tây,  nấu gà, để có được những món ăn hấp dẫn. Thưởng thức món ăn dân giã này bạn sẽ thấy khác hẳn với vị bún, phở được làm theo cách công nghiệp. Sợi mỳ dai, không tạo cảm giác khó chịu đối với người bị dạy dày. Đặc biệt lựa chọn mỳ chũ cho trẻ nhỏ rất an toàn. \r\n\r\nCAM KẾT CHẤT LƯỢNG TUYỆT ĐỐI!\r\n\r\nGiao hàng toàn quốc với phí ship cực kì hỗ trợ\r\n\r\nMỳ chũ ngủ sắc gồm 5 vị: làm từ gạo bao thai hồng\r\nThông tin dinh dưỡng/100Gr\r\n+ Calories: 109\r\n- Khoai lang\r\n- Ngô\r\n- Chùm Ngây\r\n- Đậu Biếc\r\n- Gấc\r\nTuỳ mùa sẽ có loại rau củ khác nhau\r\nCam kết: không hoá chất phẩm màu và chất bảo quản\r\n100% tự nhiên\r\n\r\nMỳ chũ 8 vị: làm từ gạo bao thai hồng\r\nThông tin dinh dưỡng/100Gr\r\n+ Calories: 109\r\n- Khoai lang\r\n- Ngô\r\n- Chùm Ngây\r\n- Đậu Biếc\r\n- Gấc\r\n- Lứt Đen\r\n- Gạo Bao Thai\r\n- Lứt Huyết Rồng\r\nTuỳ mùa sẽ có loại rau củ khác nhau\r\n\r\nKhi khách gặp bất kì vấn đề gì về sản phẩm\r\nĐừng vội đánh giá shop mà hãy nhắn tin trước cho shop để shop hỗ trợ bạn nhé!\r\nTrường hợp đôi lúc shop có lỡ gửi nhầm hàng hoặc sản phẩm bị lỗi\r\nMong bạn thông cảm, hãy nhắn cho shop liền nha, shop rất biết ơn nếu bạn làm điều đó ạ. \r\n - Chúc bạn sử dụng sản phẩm thật ngon miệng', 'mi6.png', 'mii6.jpg'),
(7, 'Trà Hoa Cúc', 30, 'Hộp', 60000, 3, 'SIÊU THỊ THẢO MỘC – Tinh Hoa Thảo Mộc Việt\r\n----------------------\r\nTrà Hoa Cúc Vàng (Hoàng Cúc) là loại thức uống có công dụng tuyệt vời đối với sức khỏe. Vị trà tính mát giúp giải tỏa căng thẳng, hỗ trợ giảm các chứng đau nhức, giúp thanh nhiệt giải độc, hạ men gan, mát gan, đau bụng kinh…\r\n\r\nTrong hỗ trợ về cao huyết áp trà hoàng cúc được coi là thảo dược tự nhiên tốt nhất, uống trà hoàng cúc trước khi đi ngủ tạo cảm giác nhẹ nhõm sảng khoái giúp ngủ sâu. Hoa cúc vàng cũng có chất kháng khuẩn, tác dụng giãn mạch giúp hạ huyết áp, giảm mỡ trong máu, làm dịu căng thẳng thần kinh. Uống trà hoàng cúc thực sự mang lại nhiều lợi ích cho người cao tuổi.\r\n\r\n• Tên sản phẩm: Trà Hoàng Cúc (Cúc Vàng Hàm Hương).\r\n• Nguồn gốc: Việt Nam.\r\n• Mùi vị: Vị thanh tự nhiên, hương thơm nhè nhẹ, dễ uống.\r\n• Quy cách đóng gói: Túi Zip 100gram, 200gram, 0,5kg và 1kg.\r\n• Hạn sử dụng: 12 tháng kể từ NSX in trên bao bì.\r\n• Có đầy đủ giấy chứng nhận ATVSTP\r\n• Check mã vạch trực tiếp trên bao bì của sản phẩm\r\n• Thành phần: Hoa Cúc sấy khô nguyên nụ tự nhiên.\r\n• Hướng dẫn bảo quản: Nơi khô ráo, thoáng mát. Tránh ánh nắng mặt trời chiếu trực tiếp.\r\n', 'tra1.png', 'trahoacuc.jpg\r\n'),
(8, 'Trà Gạo Lứt ', 30, 'Hộp', 60000, 3, 'TRÀ GẠO LỨT MIX ĐẬU ĐEN XANH LỒNG\r\nRANG TRÊN BẾP CỦI RẤT THƠM, VỊ ĐẰM RẤT NGON.\r\n\r\nThanh lọc, giải độc tố, thanh nhiệt cơ thể, giảm cân giữ dáng\r\nLợi sữa cho mẹ sau sinh\r\nLàm giảm sỏi thận, chắc khỏe, giảm hiện tượng đau đầu, cải thiện tinh thần\r\nChấm dứt tình trạng đi tiểu đêm nhiều lần\r\nGiảm cân hiệu quả, làm da sáng hồng tự nhiên\r\n\r\nCÁCH DÙNG TRÀ: dùng thay nước lọc là tốt nhất\r\nHoặc có thể uống nóng lạnh tuỳ thích\r\nLấy 2-3 muỗng cho vào ly hoặc bình\r\nĐun sôi 0,5 – 1 lít nước, sau đó bạn châm nước sôi vào ly hoặc bình giữ nhiệt ngâm trà khoảng 15 phút.\r\nChắt lấy nước uống, xác trà có thể ăn \r\nUống đậm hay nhạt, nhiều hay ít tùy thích.\r\n\r\nLưu ý: Sau 20 phút phải chắt nước trà ra ngay chứ không là thành chè nha cả nhà ', 'tra4.png', 'tragaolut.jpg'),
(9, 'Trà Gạo Lứt Hoa Cúc', 30, 'Hộp', 70000, 3, 'TRÀ HOA CÚC GẠO LỨT THANH NHIỆT, NGỦ NGON, ĐIỀU HOÀ HUYẾT ÁP 600GR - TUNA HEALTHY FOODS\r\n\r\n⁂ Sản phẩm: Trà hoa cúc gạo lứt\r\n⁂ Thương hiệu: TUNA\r\n⁂ Xuất xứ: Việt Nam\r\n⁂ Khối lượng: 600gr ( 20 túi X 30 g)\r\n⁂ Dạng bào chế: Túi trà\r\n⁂ Thành phần: Gạo lứt tím rang, đậu đen xanh lòng, đậu đỏ, kỷ tử, hoa cúc, cỏ ngọt.\r\n⁂ Hạn sử dụng: 18 tháng từ ngày sản xuất (xem trên bao bì)\r\n\r\n\r\nTÁC DỤNG TRÀ HOA CÚC GẠO\r\n- Trà gạo lứt hoa cúc thanh nhiệt, giải độc, mát gan, giúp ăn ngon ngủ ngon, da dẻ hồng hào tươi sáng.\r\n- Trà gạo lứt hoa cúc hỗ trợ và ngăn ngừa ung thư.\r\n- Trà gạo lứt hoa cúc tăng cường hệ miễn dịch, sức đề kháng của cơ thể, ngừa cảm lạnh.\r\n- Trà gạo lứt hoa cúc hỗ trợ ngăn ngừa huyết áp cao, tiểu đường, máu nhiễm mỡ, thấp khớp, gout...\r\n- Đặc biệt, trà gạo lứt hoa cúc TUNA hỗ trợ giảm cân an toàn, thon gọn vóc dáng. Vì vậy, rất tốt cho mẹ bầu và mẹ sau sinh.\r\n\r\nCÁCH DÙNG TRÀ HOA CÚC GẠO LỨT HOA CÚC \r\n- Cho 1 túi vào 1,5 lít nước đun sôi 1 phút, hoặc ngâm từ 10 - 15 phút trong nước nóng trên 80 độ C, trà sau khi đun bạn nên sử dụng trong vòng 1 ngày, có thể cho thêm đá nếu thích uống lạnh.\r\n- Bảo quản: Để nơi khô ráo, thoáng mát.\r\n', 'tra6.png', 'tragaoluthoacuc.jpg'),
(10, 'Granola siêu hạt 500gram', 100, 'Hộp', 200000, 1, 'Granola Siêu Hạt Ăn Kiêng Nofa, Ngũ Cốc Giảm Cân Dinh Dưỡng Không Đường, Óc Chó Đỏ, Dâu Tây, Thêm Mắc Ca 500gr\r\n\r\nGiúp hỗ trợ giảm cân tự nhiên, đặc biệt đảm bảo an toàn cho sức khỏe với nguyên liệu đầu vào và quy trình sản xuất đã được kiểm nghiệm và cấp chứng chỉ An toàn VSTP ISO tiêu chuẩn Quốc Tế Được mix từ 12 loại Hạt & Quả nhập khẩu nguyên vị, nướng cùng yến mạch Úc & mật ong hoa nhãn, đem đến vị thơm ngon, giòn rụm\r\n\r\nThông tin sản phẩm Thành phần Granola Nofa mix 12 loại Hạt & Quả: \r\n\r\n- Yến mạch Úc sấy mật ong giòn rụm \r\n- Hạt Macca \r\n- Hạt óc chó đỏ \r\n- Hạt óc chó vàng \r\n- Hạt hướng dương \r\n- Hạt bí xanh Hạt Điều \r\n- Hạt hạnh nhân \r\n- Mơ sấy dẻo \r\n- Nho mix 3 màu \r\n- Nam việt quất \r\n- Dâu tây \r\n\r\n\r\nĐối tượng sử dụng\r\n\r\nSử dụng được cho mọi đối tượng trong đó thích hợp với:\r\n- Người giảm cân\r\n- Người ăn kiêng\r\n- Mẹ và bé\r\n- Người tập thể thao ( ăn theo chế độ)\r\nChống chỉ định:\r\n- Người dị ứng với các loại hạt hoặc các thành phần hạt có trong sản phẩm theo chỉ định của bác sĩ\r\n\r\nHiệu quả sản phẩm\r\n\r\n- Hỗ trợ giảm cân hiệu quả\r\n- Chống oxi hóa, trẻ đẹp làn da\r\n- Bổ sung àm lượng Omega 3, chất xơ cao\r\n- Giàu Vitamin & khoáng chất\r\n- Cung cấp năng lượng dồi dào, thực đơn keto, ăn kiêng hoàn hảo\r\n- Hỗ trợ phát triển não bộ, mắt và hệ miến dịch\r\n- Cung cấp năng lượng, dinh dưỡng lành mạnh cho mẹ\r\n- Cải thiện thực đơn, ổn định huyết áp\r\n', 'sieuhat.png', 'granola1.jpg\r\n'),
(11, 'Granola nướng mật ong ', 100, 'Hộp', 180000, 1, 'MÔ TẢ SẢN PHẨM\r\nGranola nướng mật ong 35% yến mạch dành cho người mới tập ăn kiêng giảm cân healthy Lucy Food\r\nLoại Hạt - Lucy Food chính hãng\r\n- Granola, sản phẩm thuộc thương hiệu Lucy Food\r\n-Granola Lucy Food gồm 3 vị:\r\n+Granola vị matcha ( 35% yến mạch)\r\n+Granola vị socola  ( 35% yến mạch)\r\n+Granola vị vani  ( 35% yến mạch)\r\n1.Granola nướng mật ong 35% yến mạch gồm có 3 vị: ( vị matcha - vị socola - vị vani )\r\n-(1) Hạt điều Bình Thuận\r\n-(2) Hạnh nhân Úc\r\n-(3) Hạt bí xanh\r\n-(4) Yến mạch \r\n-(5) Xoài Úc sấy dẻo\r\n-(6) Nho Chile\r\n-(7) Dừa khô bến tre\r\n3. THÔNG TIN SP \r\n- Sản xuất bởi: Hộ Kinh Doanh Granola Lucy Food\r\n- Địa chỉ: 430 đường Tân Nhuệ 2, Cổ Nhuế 2, Bắc Từ Liêm, Hà Nội\r\n- Hướng dẫn sử dụng: Dùng ăn trực tiếp\r\n- Hướng dẫn bảo quản: Bảo quản nơi thoáng mát\r\n- Trọng lượng: 100g-500g\r\n- Hạn sử dụng: 6 tháng kể từ ngày sản xuất\r\n- Xuất xứ: Việt Nam \r\n\r\n3. TÁC DỤNG TUYỆT VỜI CỦA GRANOLA\r\n- Granola hỗ trợ giảmm cânn hiệu quả\r\n- Granola chống oxi hóa, trẻ đẹp làn da\r\n- Granola bổ sung àm lượng Omega 3, chất xơ cao\r\n- Granola giàu Vitamin & khoáng chất\r\n- Granola Cung cấp năng lượng dồi dào, thực đơn keto, ănn kiêngg hoàn hảo\r\n.\r\n4. TÁC DỤNG TỐT ĐỐI VỚI MẸ BẦU\r\n- Hỗ trợ phát triển não bộ, mắt và hệ miễn dịch cho trẻ\r\n- Cung cấp năng lượng, dinh dưỡng lành mạnh cho mẹ\r\n- Cải thiện thực đơn, ổn định huyết áp', 'vani2.png', 'granola0.jpg'),
(12, 'Granola Vị Matcha 500g', 100, 'Hộp', 230000, 1, 'MÔ TẢ SẢN PHẨM\r\nGRANOLA MATCHA\r\nGranola matcha với hương thơm đặc trưng của matcha ( trà xanh), kết hợp tinh tế cùng các loại hạt, yến mạch hoà trộn cùng mật ong nguyên chất. Hậu đắng của matcha  rất đặc trưng.  Matcha chứa nhiều chất chống oxy hoá, giúp làm đẹp da, cải thiện sức khoẻ.\r\n\r\nTHÀNH PHẦN: \r\nYến mạch, hạnh nhân, hạt điều, hạt bí xanh, hạt óc chó, hạt óc chó đỏ, nho khô, nam việt quất, mật ong rừng nguyên chất,  bột matcha (3%)\r\n\r\nAI CÓ THỂ DÙNG GRANOLA? \r\n- Dành cho MỌI ĐỐI TƯỢNG muốn tìm một món ăn sáng/ăn vặt tốt cho sức khỏe.\r\n- Tiết kiệm thời gian\r\n- Đặc biệt phù hợp với chế độ ăn chay, luyện tập gym/yoga, ăn kiêng, eat clean, giảm cân lành mạnh.\r\n\r\nHƯỚNG DẪN SỬ DỤNG:\r\n- Có thể  dùng vào bữa sáng hay bữa phụ hàng ngày.\r\n- Có thể dùng trực tiếp như snack, hoặc thưởng thức  ngon hơn khi dùng kèm sữa chua, bánh mì, dùng kèm sinh tố, salad.\r\n- Granola cũng có thể dùng để làm các loại bánh siêu ngon.\r\n \r\nHƯỚNG DẪN BẢO QUẢN: \r\n- Trong túi/hộp kín, nơi khô ráo thoáng mát, tránh ánh nắng trực tiếp.', 'matcha1.jpg', 'matcha2.jpg'),
(13, 'Granola Vị Chocolate 500g', 100, 'Hộp', 230000, 1, 'MÔ TẢ SẢN PHẨM\r\nGRANOLA CHOCOLATE\r\nVới yến mạch, các loại hạt sấy giòn rụm cùng mật ong và bột cacao nguyên chất. Với quy trình sấy khép kín giúp giữ được hương vị và dinh dưỡng của sản phẩm. Chocolate/cacao cùng các loại hạt cung cấp và duy trì năng lượng để làm việc. Nếu bạn là người vận động hay hoạt động trí não thì đây là nguồn năng lượng phù hợp dành cho bạn.\r\n\r\nTHÀNH PHẦN: \r\nYến mạch, hạnh nhân, hạt điều, hạt bí xanh, hạt óc chó, hạt óc chó đỏ, nho khô, nam việt quất, mật ong rừng nguyên chất, chocolate, bột cacao.( 3%)\r\n\r\nAI CÓ THỂ DÙNG GRANOLA? \r\n- Dành cho MỌI ĐỐI TƯỢNG muốn tìm một món ăn sáng/ăn vặt tốt cho sức khỏe.\r\n- Tiết kiệm thời gian\r\n- Đặc biệt phù hợp với chế độ ăn chay, luyện tập gym/yoga, ăn kiêng, eat clean, giảm cân lành mạnh.\r\n\r\nHƯỚNG DẪN SỬ DỤNG:\r\n- Có thể  dùng vào bữa sáng hay bữa phụ hàng ngày.\r\n- Có thể dùng trực tiếp như snack, hoặc thưởng thức  ngon hơn khi dùng kèm sữa chua, bánh mì, dùng kèm sinh tố, salad.\r\n- Granola cũng có thể dùng để làm các loại bánh siêu ngon.\r\n \r\nHƯỚNG DẪN BẢO QUẢN: \r\n- Trong túi/hộp kín, nơi khô ráo thoáng mát, tránh ánh nắng trực tiếp.\r\n\r\nHẠN SỬ DỤNG\r\n- 6 tháng kể từ ngày sản xuất.\r\n- Sử dụng trong vòng 30 ngày sau khi mở sản phẩm để có chất lượng tốt nhất.\r\n\r\nCÔNG DỤNG CỦA GRANOLA CỦA THE FIT TUNA\r\n- Chứa hàm lượng chất xơ cao, nguồn protein từ thực vật ( các loại hạt).\r\n- Đa dạng các loại hạt nguồn cung cấp chất béo tốt giúp giảm cholesterol xấu, giảm nguy cơ mắc bệnh tim mạch.\r\n- Giúp ngăn ngừa táo bón, hạn chế ợ hơi, trào ngược dạ dày.\r\n- Hỗ trợ giảm cân, giúp khống chế cơn thèm ăn, hạn chế ăn vặt. \r\n- Phù hợp với mọi đối tượng: Eat clean, ăn chay, tập luyện, thích ăn ngon, nhanh gọn.\r\n- Đa dạng hương vị, sản phẩm thơm ngon, nướng mới mỗi ngày.', 'socola1.jpg', 'socola2.jpg'),
(19, 'Trà gạo lứt Quê Việt', 50, 'Hộp', 179000, 3, '\r\n– Giúp thanh lọc gan, thải độc cơ thể, giúp làn da trở nên tươi sáng và hồng hào hơn.\r\n\r\n– Hỗ trợ bệnh nhân điều trị ung thư, bị bệnh tiểu đường, viêm gan và suy nhược thần kinh. – Hỗ trợ giảm cân an toàn.\r\n\r\n– Tốt cho người bệnh gout và phong thấp.\r\n\r\n– Tăng cường chức năng của thận, người lớn sẽ không bị tiểu đêm.\r\n\r\nCÁCH DÙNG\r\n\r\n– Cho 1 túi trà vào 1 lít nước đun sôi 5 phút, hoặc ngâm 10-15 phút trong nước nóng trên 80 độ c.\r\n\r\n– Trà sau khi đun bạn nên sử dụng trong vòng một ngày. Có thể c', 'tragaolut1.jpg', 'tragaolut2.jpg'),
(20, 'Trà Kombucha', 90, 'Long', 132000, 3, '❤️ NHỮNG LỢI ÍCH CỦA KOMBUCHA\r\n\r\n1, Nguồn cung cấp lợi khuẩn Probiotic Trong quá trình Kombucha lên men, trà nãy cũng giải phóng ra Probiotic và một hàm lượng cao axit, vitamin có lợi cho sức khỏe. Vì thế bạn cũng có thể sử dụng trà Kombucha như một loại thức uống giúp ăn ngon, tiêu hóa tốt hơn.\r\n\r\n2, Có thể ngăn ngừa sự lây lan của tế bào ung thư Trà Kombucha có chứa hàm lựa chất oxy hóa cao và nồng độ polyphenol (hợp chất có được trong quá trình nuôi Scoby trong trà)\r\n\r\n3, Tăng cường hoạt động', 'kombucha1.jpg', 'kombucha2.jpg'),
(21, 'Trà detox hoa quả', 72, 'Gói', 147000, 3, 'Trà detox Có công dụng giúp: Thanh lọc cơ thể, giúp giữ dáng, đẹp da\r\n\r\nCách sử dụng:\r\n\r\n1 : Bóc 1 gói detox vào bình\r\n\r\n2 : Cho vào bình đổ nước nóng 70 độ\r\n\r\n3 : Đóng nắp, hãm khoảng 15~30p\r\n\r\n4 : Cho vào tủ lạnh, để lạnh theo sở thích và\r\n\r\nSét trà gồm;\r\n\r\n30 gói trà detox hoa quả\r\n\r\n1 bình pongdang 1 lít kèm túi vải đựng bình chuyên dụng pha trà nên chịu nhiệt nước nóng 100 độ\r\n\r\n5 gói đường', 'detox1.jpg', 'detoc2.jpg'),
(22, 'Trà hoa nhài', 100, 'Gói', 90000, 3, 'Tên sản phẩm: Trà Hoa Nhài (Hoa Nhài).\r\nNguồn gốc: Việt Nam.\r\nMùi vị: Vị ngọt tự nhiên, tính mát, hương thơm nhè nhẹ, dễ uống.\r\nQuy cách đóng gói: Túi Zip 100gram, 200gram, 0,5kg và 1kg.\r\nHạn sử dụng: 12 tháng kể từ NSX in trên bao bì.\r\nCó đầy đủ giấy chứng nhận ATVSTP\r\nCheck mã vạch trực tiếp trên bao bì của sản phẩm\r\nThành phần: Hoa nhài sấy khô nguyên nụ tự nhiên.\r\nHướng dẫn bảo quản: Nơi khô ráo, thoáng mát. Tránh ánh nắng mặt trời chiếu trực tiếp.\r\n\r\nCÔNG DỤNG CỦA TRÀ HOA NHÀI:\r\n- Trà hoa n', 'trahoanhai1.jpg', 'trahoanhai2.jpg'),
(23, 'Hạt Phỉ', 79, 'Gói', 69000, 1, 'Hạt phỉ có thể giúp giữ cho trái tim của bạn khỏe mạnh!\r\nChúng chứa nhiều chất béo không bão hòa đơn, có thể giúp giảm mức cholesterol xấu và giảm nguy cơ mắc bệnh tim.\r\nHạt phỉ rất tốt để nấu ăn cùng. Chúng không chỉ thơm ngon khi chỉ được rang đơn thuần mà còn là nguyên liệu tuyệt vời để chế biến nhiều loại nước sốt như Romesco, phết hạt và các món nướng.\r\nNgoài ra, ăn hạt phỉ có thể giúp cải thiện tình trạng vitamin E ở người lớn tuổi.\r\n\r\nHướng Dẫn Sử Dụng: Dùng trực tiếp hoặc thêm vào ngũ cốc, muesli, sinh tố, salad và các công thức làm bánh và sữa hạt.\r\nHạt phỉ có thể giúp giữ cho trái tim của bạn khỏe mạnh!\r\nChúng chứa nhiều chất béo không bão hòa đơn, có thể giúp giảm mức cholesterol xấu và giảm nguy cơ mắc bệnh tim.\r\nHạt phỉ rất tốt để nấu ăn cùng. Chúng không chỉ thơm ngon khi chỉ được rang đơn thuần mà còn là nguyên liệu tuyệt vời để chế biến nhiều loại nước sốt như Romesco, phết hạt và các món nướng.\r\nNgoài ra, ăn hạt phỉ có thể giúp cải thiện tình trạng vitamin E ở người lớ', 'hatphi1.jpg', 'hatphi2.jpg'),
(24, 'Hạt sen', 100, 'Hộp', 169000, 1, '“Hạt sen sấy vừa bổ vừa thanh  Tan trên đầu lưỡi ngọt lành hương xưa”\r\nGói gọn trong một hạt sen nhỏ bé là những dưỡng chất vô cùng quý giá được ví von là hạt ngọc trời của thiên nhiên.\r\nVới giá trị dinh dưỡng dồi dào giúp an thần, ngủ ngon, tốt cho tim mạch và huyết áp... Đó cũng là lý do mà hạt sen được yêu thích và trở thành món ăn phổ biến trong mọi gia đình Việt Nam.\r\n- Thời gian bảo quản lâu nên dễ dàng được dùng chế biến thực phẩm. Những món ăn dùng loại hạt sen này thường là sâm bổ lượng, cơm sen, cháo hạt sen, chè hạt sen đậu xanh,…\r\n- Đặc biệt, hạt sen sấy giòn ăn liền hạt to đều, là hàng loại 1, ăn giòn rụm, thơm ngon và không bị ngán. Có thể ăn liền mà không cần qua chế biến nên có thể sử dụng làm món ăn vặt mọi lúc mọi nơi.\r\n- Sản phẩm hạt sen sấy thích hợp làm quà tặng cho ông bà, cha mẹ...', 'hatsen1.jpg', 'hatsen2.jpg'),
(25, 'Yến mạch', 36, 'Gói', 20000, 2, 'Được sản xuất ở dạng nguyên chất, không cần trải qua quy trình sơ chế tách vỏ hay rửa nước nào cả, rất bổ dưỡng và cần thiết để sử dụng trong gia đình. Yến mạch là một trong những loại thực phẩm lành tính và ít gây dị ứng nhất, chứa thành phần dinh dưỡng cao, không trộn lẫn các hóa chất gây nguy hại đến sức khỏe. Dùng được cho mọi đối tượng, đặc biệt rất tốt cho trẻ em ở lứa tuổi ăn dặm và những người cao huyết áp, tim mạch, hay muốn làm đẹp da. Bổ sung protein giúp cung cấp năng lượng, nâng cao sức khỏe, phát huy trí não và tăng cường thể chất tối ưu. Nguồn chất xơ dồi dào giúp cải thiện hệ tiêu hóa, không gây thừa cân, ngăn ngừa chứng táo bón và các bệnh về đường ruột, Hàm lượng vitamin B giúp bổ sung dưỡng chất để trí não phát triển và duy trì cơ thể khỏe mạnh, dẻo dai + Giàu hàm lượng các khoáng dưỡng chấtbao gồm sắt, magie, canxi, photpho… giúp làm đẹp da, phát triển hệ xương, tốt cho trí não, bảo vệ tim mạch, và tăng cường hệ miễn dịch.\r\nXuất xứ: Đức\r\n\r\nHạn sử dụng: 24 tháng\r\n\r\nTrọng lượng: 500g\r\n\r\nGiảm cân đặc biệt: Không cholesterol, Không gluten, Tốt cho sức khỏe\r\n\r\nKích Cỡ Gói: 500G/GR\r\n\r\n', 'yenmach1.jpg', 'yenmach2.jpg'),
(26, 'Mỳ váng đậu', 40, 'Gói', 23100, 2, 'MÌ VÁNG ĐẬU - SỬ DỤNG ĂN KETO HIỆU QUẢ\r\n\r\nCó thể ăn thay mì tôm mà ko có chất phụ gia,không phẩm màu , không chất bảo quản. rất tốt cho cơ thể ,đặc biệt phù hợp những người muốn giảm cân và ăn chay.\r\n\r\n♨️ MÌ VÁNG ĐẬU KHÔ\r\n\r\n♨️ Khối lượng tịnh: 100gr, gói hút chân không\r\n\r\nCÁCH NẤU :\r\n\r\n- Ngâm mì với nước 5-10 phút cho sợi mì mềm ra.\r\n\r\n- Nếu nấu canh thì chế biến bình thường.\r\n\r\nNếu dùng để xào hay trộn thì trần với nước sôi tầm 3-4 phút sau đó vớt ra chế biến ( thêm rau củ quả,thịt,gia vị...tùy ý thích của từng người nha )\r\nSản phẩm mì váng đậu và váng đậu lá đã được sấy khô, tuy nhiên sản phẩm không có chất bảo quản nên vẫn sẽ dễ hư hỏng nếu bảo quản không đúng cách. Nguyên tắc quan trọng khi bảo quản thực phẩm khô là bạn nên bảo quản ở nơi khô ráo và thoáng mát.\r\n\r\nTuy nhiên để bảo quản được lâu và tránh ẩm mốc thì nên:\r\n\r\n1. Sau khi nhận hàng khách nên kiểm tra, nếu còn ẩm bạn nên phơi thêm 1-2 nắng để khô hoàn toàn ( nếu khách ăn ngay trong thời gian ngắn và muốn bảo quản ở nhiệt độ thường ). 2. Đối với mì váng đậu: Tốt nhất là bảo quản trong ngăn đông của tủ lạnh nhé. Ăn đến đâu thì mình rã đông đến đó. Bạn không cần phải quá lo lắng về việc mì sẽ bị đông cứng, ngược lại, do thực phẩm khô chứa ít nước cho nên sẽ trở nên dẻo và thơm ngon hơn sau khi để ở ngăn đá.', 'vangdau1.jpg', 'vangdau2.jpg'),
(27, 'Phở gạo lứt', 40, 'Gói', 60000, 2, 'PHỞ LỨT\r\n\r\n                                                         =========\r\n\r\n☘️ Thành phần: Làm từ 100% gạo lức đỏ, trà Bancha, muối hầm và nước sạch\r\n\r\n☘️ Phở Gạo Lứt chứa các nguồn khoáng chất rất như Magie giúp điều chỉnh thần kinh và cơ, Mangan, Selen, … Cung cấp các vitamin, acid amin có trong sản phẩm, phù hợp với các bệnh nhân về đường tiêu hóa, tim mạch, viêm khớp, suy thận, tiểu đường, ...\r\n\r\n☘️ Ngoài ra Phở Gạo Lứt chứa rất nhiều Magie tác dụng chắc xương, lượng Magie có trong gạo lức giúp cho cơ thể kiểm soát đường trong máu. Do đó nhiều chuyên giá bác sĩ khuyên dùng cho bệnh nhân bị loãng xương, tiểu đường và thái hóa\r\n\r\n☘️ Dùng được cho cả người lớn lẫn trẻ em. Bởi vì Phở được làm nguyên chất từ Gạo Lứt Huyết Rồng 100% Giá trị dinh dưỡng trong 100g PHỞ gạo lứt như sau:  • Năng lượng: 380 calo (calo từ chất béo 18)  • Carbohydrates: 80g  • Chất béo: 2g  • Natri: 10mg (1% DV)  • Chất xơ: 4g (16% DV)  • Protein: 8g  • Canxi: 40mg (4% DV)  • Sắt: 0,7mg (9% DV)  Gạo lứt huyết rồng chứa nhiều chất đạm, chất xơ cùng các vitamin (B1, B2, B3, B5, B6…), các acid (paraaminobenzoic, Folic, Phytic, Omega 3, Omega 6, Omega 9…), khoáng chất (canxi, sắt, magie, selen,…) rất tốt cho sức khỏe. Phở gạo lứt huyết rồng được sản xuất từ những hạt gạo lứt huyết rồng đỏ được tuyển chọn kĩ lưỡng, sau đó mang đi ủ và chế biến thành món bún tươi. Phở gạo lứt đỏ có thể kết hợp cùng một số nguyên liệu khác để tạo nên những món bún ngon, vừa làm cho nền ẩm thực Việt Nam thêm phong phú, vừa tăng giá trị chất lượng món ăn lên cao hơn. \r\nNhững lợi ích tuyệt vời khi duy trì sử dụng Phở Gạo Lứt Đỏ Huyết Rồng trong thực đơn mỗi ngày: \r\n\r\n☘️ Giảm cân, giảm mỡ khi duy trì một chế độ ăn với Phở gạo lứt. \r\n\r\n☘️ Giảm cholesterol trong máu. \r\n\r\n☘️ Quá trình ủ bún sinh ra nhiều vi sinh có lợi cho đường ruột cho nên hệ tiêu hóa, chức năng gan của sẽ được cải thiện nhiều hơn. \r\n\r\n☘️ Có nhiều loại vitamin như B1, B3, B6, E,… và nhiều chất khác như Mangan, Fe, chất xơ,… hỗ trợ tốt cho người bệnh', 'pholut1.jpg', 'pholut2.jpg'),
(28, 'Gạo lứt trắng hữu cơ cao cấp/ECOBA', 18, 'Gói', 102000, 2, '13 CÔNG DỤNG GẠO LỨT:\r\n1. Gạo lứt có tác dụng bảo vệ tế bào bị xâm hại khỏi gốc tự do \r\n2.Tác dụng của gạo lứt tốt cho người bị bệnh tiểu đường \r\n3. Giảm cholesterol \r\n4. Tăng cường miễn dịch là một trong những tác dụng của gạo lứt \r\n5. Giảm nguy cơ mắc ung thư \r\n6. Cải thiện hệ tiêu hóa \r\n7. Giảm cân \r\n8. Giải độc cơ thể do các chất độc hại \r\n9. Cải thiện chức năng gan \r\n10. Giảm sỏi thận, giảm loãng xương \r\n11. Cải thiện thị giác \r\n12. Tăng cường trí óc \r\n13. Làm đẹp\r\n - Cách nấu: Trước tiên chúng ta cần đãi gạo sạch sẽ nhặt sạn, bỏ chấu nếu còn. Đãi đỗ đỏ, hạt sen, rửa sạch phổ tai và ngâm phổ tai khoảng 3 phút cho phổi tai nở ra. Sau khi đãi sạch chúng ta trộn đều gạo lứt, đỗ đỏ, hạt sen cùng muối hầm và đổ vào nồi đất cuối cùng ta cho miếng phổ tai lên trên cùng và đổ nước vừa đủ tráng để cơm bị nhão hoặc khô. Đặt nồi đất chứa đầy đủ những nguyên liệu trên vào trong nồi gang rồi đổ nước ngập 4/3 nồi đất Ta bắt đầu đặt lên bếp để đun đến khi nào thấy sôi khoảng 10 phút ta giảm bớt lửa Nồi cơm hấp cách thủy sôi liu riu khoảng 6 tiếng thấy nước trong nồi gang cạn gần hết là đạt yêu cầu Lúc này chúng ta lấy nồi đất phía trong ra để thưởng thức được rồi đó.', 'gao1.jpg', 'gao2.jpg'),
(29, 'Trà gạo lứt xạ đen', 27, 'Hộp', 30000, 3, '1. Tên sản phẩm: Trà gạo lứt xạ đen.\r\n2. Đơn vị chịu trách nhiệm sản xuất:\r\nNhà sản xuất Hà Tiên - Chùa Hà, Vĩnh Yên, Vĩnh Phúc\r\n3. Xuất xứ: sản xuất tại Việt Nam Trà gạo lứt xạ đen giảm cân, trà gạo lứt huyết rồng giảm mỡ bụng , thanh lọc cơ thể, an thần ngủ ngon có các thành phần: Gạo lứt huyết rồng - Xạ đen Hòa Bình - Hoa nhài sấy lạnh - Thảo quyết minh, cỏ ngọt.\r\nTrà gạo lứt xạ đen giảm cân, trà gạo lứt huyết rồng giảm mỡ bụng , thanh lọc cơ thể, an thần ngủ ngon công dụng: -Thanh lọc cơ thể - Giúp ngủ ngon, an thần, ngủ sâu giấc - Giảm cân lấy lại vóc dán - Giúp làn da luôn tươi trẻ, căng mượt - Giúp nữ dáng đẹp, eo thon. Phù hợp với những người nóng gan, bốc hỏa thời kì sau sinh. Rất tốt cho phụ nữ sau sinh Trà gạo lứt xạ đen giảm cân, trà gạo lứt huyết rồng giảm mỡ bụng , thanh lọc cơ thể, an thần ngủ ngon\r\n- Cách dùng: -Lấy 2-3 muỗng (20-30gr) trà hoa ngũ cốc cùng 1 lít nước sôi uống cả ngày - Có thể cho vào ngăn mát để uống ngon hơn Bảo quản trà hoa ngũ cốc. Để nơi thoáng mát, tránh ẩm ướt\r\n- SHOP CAM KẾT:  Hàng có sẵn, giao hàng ngay khi nhận được đơn - Hoàn tiền nếu sản phẩm không giống với mô tả - Chấp nhận đổi hàng khi kích cỡ không vừa - Giao hàng trên toàn quốc, nhận hàng trả tiền\r\n- Trà gạo lứt xạ đen giảm cân, trà gạo lứt huyết rồng giảm mỡ bụng , thanh lọc cơ thể, an thần ngủ ngon có các thành phần:\r\n- Gạo lứt huyết rồng\r\n- Xạ đen Hòa Bình\r\n- Hoa nhài sấy lạnh\r\n- Thảo quyết minh, cỏ ngọt.\r\n- Trà gạo lứt xạ đen giảm cân, trà gạo lứt huyết rồng giảm mỡ bụng , thanh lọc cơ thể, an thần ngủ ngon công dụng:\r\n- Thanh lọc cơ thể\r\n- Giúp ngủ ngon, an thần, ngủ sâu giấc\r\n- Giảm cân lấy lại vóc dán\r\n- Giúp làn da luôn tươi trẻ, căng mượt\r\n- Giúp nữ dáng đẹp, eo thon\r\n- Phù hợp với những người nóng gan, bốc hỏa thời kì sau sinh. Rất tốt cho phụ nữ sau sinh Trà gạo lứt xạ đen giảm cân, trà gạo lứt huyết rồng giảm mỡ bụng , thanh lọc cơ thể, an thần ngủ ngon cách dùng:\r\n- Lấy 2-3 muỗng (20-30gr) trà hoa ngũ cốc cùng 1 lít nước sôi uống cả ngày - Có thể cho vào ngăn mát để uống ngon hơn Bảo quản trà hoa ngũ cốc - Để nơi thoáng mát, tránh ẩm ướt', 'tragaolutgaoden1.jpg', 'tragaolutgaoden2.jpg'),
(30, 'Cacao Detox CACAOMI', 30, 'Hộp', 245000, 3, '- Phân loại: 3 gói lẻ dùng thử , Hộp 20 gói (66g)\r\n\r\n- Ngày sản xuất: in trên bao bì\r\n\r\n- Hạn sử dụng: 1 năm kể từ ngày sản xuất\r\n\r\n- Xuất xứ: Việt Nam\r\n\r\n- Thành phần: Hạt cacao rang, Đông Trùng Hạ Thảo, Nụ Hoa Hòe, Hoa Cúc, Hoa Nhài, Cỏ Ngọt, Gừng\r\n\r\n- Thanh lọc cơ thể, tăng cường sức khỏe đề kháng. Hỗ trợ giảm cân, giảm mỡ, kiểm soát cân nặng. Có thể kết hợp sử dụng trong quá trình ăn kiêng giảm cân theo chế độ Keto, Low Carbs, Eat Clean...\r\n? CÔNG DỤNG CACAO DETOX:\r\n\r\nHơn cả một thức uống, Cacao Detox mang đến cảm giác đầy sức sống và có lợi cho sức khỏe mỗi ngày. Các chất Polyphenol, Flavanol, Theobromine có trong hạt cacao là những yếu tố tác động đến hệ miễn dịch, khả năng thanh lọc, sản sinh năng lượng, chống oxy hóa, giảm lượng cholesterol xấu và kiểm soát năng lượng.\r\n\r\n? Cacao detox được kết hợp từ 7 nguyên liệu từ thiên nhiên với các thành phần sau:\r\n\r\n+ Thành phần chính: Hạt cacao nguyên chất.\r\n\r\n+ Đông Trùng Hạ Thảo:\r\n\r\n+ Nụ Hoa Hòe:\r\n\r\n+ Hoa Cúc\r\n\r\n+ Hoa Nhài\r\n\r\n+ Cỏ ngọt\r\n\r\n+ Gừng\r\n\r\n? HƯỚNG DẪN SỬ DỤNG:\r\n\r\nLấy một gói Cacao Detox cho vào bình, chế một lượng nước nóng vừa đủ để tráng bình và túi lọc, sau đó bỏ nước tráng đi. Cho 700ml nước nóng vào bình, chờ từ 10-15phút để Cacao Detox ngấm ra nước. Dùng làm thức uống hàng ngày, mỗi ngày khoảng 2 gói.', 'tracacao1.jpg', 'tracacao2.jpg'),
(31, 'Bánh Bao Nguyên Cám', 26, 'Set', 130000, 4, 'Set 5 bánh đủ vị (khác nhau ở bò trứng cút hoặc bò phô mai) SET A (gà, bò cút, xá xíu, ruốc gà, hải sản) SET B (gà, bò phômai, xá xíu, ruốc gà, hải x ?Bánh bao nguyên cám được biết tới là một loại bánh có thể bổ sung lượng dinh dưỡng nhưng không có quá nhiều calo, nhờ giữ lại lớp cám ngoài hạt nên sẽ này cung cấp đầy đủ chất xơ, khoáng chất cùng vitamin thiết yếu và giúp bạn no lâu hơn ?Bánh bao nguyên cám tuy đều dùng loại nguyên liệu chính là bột nguyên cám nhưng mỗi nơi đều có công thức và quy trình sản xuất khác biệt, từ đó mà chất lượng cũng khác nhau ít nhiều. Bánh từ nhà @mamapicked cam kết không bột mì không dầu hay “mỡ trừu” nhưng vẫn đảm bảo vị ngon mềm xốp của bánh.\r\n\r\n? Nếu ai đã từng thưởng thức qua sản phẩm của tiệm mình thì chắc hẳn sẽ thấy ngay sự khác biệt: bánh rất mềm không hề khô , bánh rất nặng tay(trọng lượng bánh 120g vừa đủ cho 1 bữa ăn không quá ít), nhân bánh nhiều vỏ vừa không quá dày.\r\n\r\n?ĐIỀU ĐẶC BIỆT Bánh được lên men tự nhiên chứa hàm lượng Gluten thấp hơn nên có thể giúp dễ dung nạp được đối với cơ thể của những người nhạy cảm với Gluten. Bánh luôn được làm tươi mới mỗi ngày để đảm bảo chất lượng khi đến tay khách hàng, hy vọng rằng sẽ luôn được mọi người tin yêu và lựa chọn ?', 'banhbao1.jpg', 'banhbao2.jpg'),
(32, 'Bánh dừa nướng', 20, 'Hộp', 69000, 4, '- HƯƠNG VỊ Bánh dừa nướng có màu nâu vàng, giòn rụm với hương vị thơm béo đặc trưng của dừa.\r\n- THÀNH PHẦN Dừa, bột nếp, đường mía tự nhiên, vani. HƯỚNG DẪN SỬ DỤNG Dùng trực tiếp sau khi mở hũ.\r\n- HƯỚNG DẪN BẢO QUẢN Bảo quản nơi khô ráo, thoáng mát.\r\n- KHỐI LƯỢNG TỊNH 170g 400g\r\n- HẠN SỬ DỤNG 12 tháng kể từ ngày sản xuất\r\n- Lấy cảm hứng từ vùng đất Quảng Nam mưa nắng, Bánh dừa nướng GUfoods mang trọn vị của thức bánh xứ Quảng quê hương, giòn rụm, thơm ngon, lay động vị giác lẫn khứu giác của người thưởng thức.\r\nĐẶC ĐIỂM NỔI BẬT\r\n✓ Đậm vị truyền thống bánh dừa nướng Quảng Nam\r\n✓ Ít ngọt, giòn rụm, thơm ngon\r\n✓ Không phụ gia / chất bảo quản, an toàn cho sức khoẻ\r\n✓ Không chiên qua dầu, không cholesterol\r\n✓ Quy trình chế biến sạch, đảm bảo an toàn vệ sinh thực phẩm\r\n✓ Sản phẩm dễ bị vỡ khi vận chuyển xa bằng các kênh vận chuyển thông thường, bạn cân nhắc trước khi đặt nhé', 'banhdua1.jpg', 'banhdua2.jpg'),
(34, 'Vỏ bánh tortilla nguyên cám', 26, 'Gói', 120000, 4, 'Sản phẩm homemade , bảo quản ngăn mát 7 ngày , ngăn đông 1 tháng , vui lòng lưu ý đây là hàng bánh tươi home made không phải sản phẩm công nghiệp tortilla thường được sử dụng để cuốn cùng các loại rau và thịt cùng sốt là món ăn quen thuộc của mexico .Nói đến ẩm thực Mexico không thể không nhắc đến Tortilla, loại bánh mì dẹt được làm từ bột bắp – thực phẩm chủ yếu của người Mexico kể từ thời tiền Columbus (1442). Hơn 104 triệu dân đất nước này ăn Tortilla mỗi ngày, như người Việt Nam ăn cơm và người Pháp không thể thiếu bánh mì vậy. Bạn có thể làm nhân cho bánh Tortilla này với rất nhiều loại nguyên liệu khác như: súp, cà ri, cá hồi xông khói, gà nướng, thịt xông khói, tôm cùng các loại rau củ quả như cà chua, cà rốt, ớt ngọt, ôliu, quả bơ, rau sống… (kết hợp với vị nước xốt Guacamole từ bơ). Vỏ bánh Tortilla còn làm vỏ bánh cho các món Fajitas, Burritos và Enchiladas\r\n', 'vobanh1.jpg', 'vobanh2.jpg'),
(35, 'Bánh Bông Lan Ăn Kiêng Không Đường Kính Không Tinh Bột', 25, 'Hộp', 65000, 4, '- Thành phần: Trứng gà, bột hạnh nhân, dầu ăn, đường kiêng, vani\r\n\r\n- Thành phầm sẽ có thêm các nguyên liệu: Chà bông ăn kiêng, sốt dầu trứng, trứng muối, phô mai bò cười.\r\n\r\nTất cả toppings đều do Bếp tự làm ạ\r\n\r\n- Bảo quản 5-7 ngày ngăn mát tủ lạnh\r\n', 'banhbonglan1.jpg', 'banhbonglan2.jpg'),
(36, 'Bánh mì đen ăn kiêng', 26, 'Gói', 65000, 4, 'Được làm từ bột lúa mạch đen và bột mì nguyên cám chứa chất xơ ăn kiêng, tốt cho sức khỏe. Bánh được làm rất dễ ăn, không khô cứng như các loại bánh mì đen thường thấy. 500g bánh gồm có 11 gói bánh, mỗi gói bánh có 2 lát.', 'banhmi1.jpg', 'banhmi2.jpg'),
(37, 'Bánh Biscotti', 39, 'Gói', 349000, 4, 'Bánh BISCOTTI nguyên cám không đường - ăn vặt giảm cân hiệu quả\r\nGồm 3 vị: truyền thống - trà xanh - chocolate Thành phần: bột nguyên cám, dầu dừa, bơ lạt TH , trứng gà, mật ong, các loại hạt ngũ cốc dinh dưỡng như hạt hạnh nhân, hạt điều, hạt bí, hạt hướng dương, việt quất, nho khô, vanil, trà xanh, cacao, chocolate.\r\nBánh Biscotti phù hợp với:\r\n* Những người bận rộn, không có nhiều thời gian chuẩn bị bữa ăn sáng * Người thường xuyên tập gym, yoga\r\n* Những người muốn ăn vặt nhưng sợ tăng cân\r\n* Người theo chế độ ăn lành mạnh eat-clean, keto, das\r\n* Người tiểu đường Ăn cùng với sữa tươi, sữa chua, ăn liền\r\nHSD 06 tháng\r\nBiscotti của Beautiful-Health được tạo ra với công thức ý, chuẩn healthy phù hợp với khẩu vị của người Việt, độ giòn vừa phải, không chất béo. Đặc biệt hơn nữa là với các thành phần lành mạnh đúng với tiêu chí ăn ngon, ăn khoẻ, ăn đẹp:\r\n✔️bột nguyên cám\r\n✔️hạnh nhân\r\n✔️hạt bí xanh\r\n✔️nho đen\r\n✔️nho vàng \r\n✔️việt quất\r\n✔️mật ong\r\n✔️trứng gà\r\nMón này có thể dùng để ăn sáng hoặc ăn vặt trong ngày, đảm bảo đủ dinh dưỡng và năng lượng. Bánh cung cấp lượng caloris tốt nên giúp bổ sung năng lượng ho các bạn tập gym, hoạt động thể thao mạnh.\r\n Hạn sử dụng sản phẩm: 2 Tháng kể từ ngày sản xuất.  Ngày sản xuất: in trên bao bì', 'banhbi1.jpg', 'banhbi2.jpg'),
(38, 'Bánh gạo lứt ngũ cốc', 30, 'Gói', 139000, 4, 'Bánh gạo lứt ngũ cốc ăn kiêng giảm cân rong biển chà bông Vietpurity, granola dạng thanh, ăn vặt healthy, eatclean Bánh gạo lứt hạt và rong biển, chà bông có vị mặn nhẹ dễ ăn, vị ngọt nhẹ thanh của mật ong, cấu trúc giòn nhẹ - thích hợp ăn sáng, ăn xế giúp bổ sung protein, chất béo cho cơ thể                      \r\n            --------------------------\r\nCÔNG DỤNG: - Thanh gạo lứt ngũ cốc cung cấp nhiều khoáng chất và vitamin cho khẩu phần ăn. Giúp cân đối dinh dưỡng, tốt cho sức khỏe. Sản phẩm bổ sung chất đạm và chất xơ, đủ chất cho người đang ăn kiêng, giảm cân. Tốt cho tim mạch, người mắc bệnh huyết áp. - Sản phẩm đã được chế biến sẵn rất tiện lợi khi sử dụng và tiết kiệm tối đa thời gian cho người bận rộn, người  tập gym, chơi thể thao, vận động mạnh. Thích hợp sử dụng làm bữa ăn họp mặt, ăn vặt hay làm quà tặng người thân, bạn bè. Tiện lợi, gọn nhẹ, thơm ngon phù hợp với mọi lứa tuổi. Có thể mang đi xa, du lịch & picnic - Thanh gạo lứt ngũ cốc 100% không chứa chất bảo quản. Bạn có thể hoàn toàn yên tâm sử dụng hằng ngày. Sử dụng cho mọi đối tượng, phù hợp với người ăn kiêng, giảm cân.                              -------------------------- \r\nHƯỚNG DẪN SỬ DỤNG: Dùng trực tiếp vào bữa sáng hoặc bữa phụ, thích hợp cho người ăn kiêng, mẹ bầu và người tiểu đường.\r\nMÔ TẢ SẢN PHẨM\r\n* ĐÓNG GÓI: Túi hút chân không 500GR\r\n* NGUỒN GỐC: Việt Nam\r\n* HẠN SỬ DỤNG: 6 tháng (sử dụng tốt nhất trong 3 tháng đầu)\r\n* BẢO HÀNH: Đổi trả miễn phí với trường hợp bao bì hư hỏng, bong tróc và đổi trả khi sản phẩm không đúng như cam kết về sản phẩm và cam kết bán hàng của shop.\r\n* BẢO QUẢN: nơi thoáng mát, tránh ánh nắng chiếu trực tiếp. Sau khi dùng nhớ đóng kĩ nắp tránh không khí lọt vào.\r\n--------------------------\r\nCAM KẾT VỀ SẢN PHẨM :  Sản xuất theo công nghệ khép kín đạt chuẩn an toàn thực phẩm, không chất bảo quản\r\n✔️Đây Không Phải Lời Hứa Mà Là Sự Cam Kết\r\n✔️Sản phẩm có nguồn gốc hoàn toàn từ thiên nhiên\r\n✔️Hoàn tiền NGAY nếu không ưng ý về sản phẩm', 'banhgao1.jpg', 'banhgao2.jpg'),
(40, 'Syrup chocolate Hershey\'s không đường', 26, 'Hộp', 240000, 5, 'Vì là cacao không đường nên sẽ có vị chua nhẹ do acid có sẵn trong cacao. Trong quá trình sản xuất đã được kiềm hoá để giảm vị chua và đắng của cacao . Bạn đừng lo khi nếm lần đầu thấy chua chua nhé???\r\n? Một trong những loại chocolate syrup nổi tiếng nhất thế giới, đến từ tập đoàn lừng lẫy The Hershey\'s Company.\r\n? Sốt béo thơm đặc quánh cực kì chất lượng và hấp dẫn, sốt Hershey’s không đường có vị đắng hơn xíu so với loại có đường , như người Mỹ thường đùa nhau đây là loại thực phẩm \"gây nghiện\" hàng đầu luôn phải có trong tủ lạnh \r\n? Có thể dùng sốt Hershey\'s để pha chế các loại thức uống như cà phê, cocktail, sinh tố, sữa lắc, blended, làm kem, bánh ngọt, , salad trái cây , trang trí các loại bánh hay đơn giản là rưới lên sandwich/ bánh mì cho bữa sáng ngon tuyệt ????.\r\nPhù hợp với người ăn kiêng, tập gym, ăn kiêng đường.', 'sot1.jpg', 'sot2.jpg'),
(41, 'Muối vừng đặc biệt ăn eat clean siêu ngon', 17, 'Hộp', 69000, 5, 'MUỐI VỪNG ĐẶC BIỆT SIÊU NGON\r\n- Quy cách: hộp 500gr\r\n- Xuất xứ: Việt Nam\r\n- NSX: In trên bao bì\r\n- HSD: 1 tháng Chứng chỉ : Ngon vô đối Khác với muối vừng thông thường ta hay ăn , muối vừng đặc biệt không chỉ có lạc , vừng đen , vừng trắng mà còn có thịt nạc, tép, lá chanh, súp hảo hảo và một số gia vị khác, tạo nên một món muối vừng ngon hơn muối vừng truyền thống rất nhiều ??', 'muoivung1.jpg', 'muoivung2.jpg'),
(42, 'Gia vị ăn kiêng 0 calo Weber 156g có combo 5 vị dùng thử', 34, 'Hộp', 205000, 5, 'Gia vị ăn kiêng WEBER 0 Calo từ Mỹ, thiết kế dành cho người có mục tiêu giảm cân/giữ dáng, nghiêm túc với chế độ ăn, chế độ dinh dưỡng của mình. ?? Ưu điểm: không đường, không chất béo, không gluten, không calo ,lượng sodium cực thấp hoặc không có, điều này giúp cơ thể hạn chế tích nước dưới da. Tốt cho việc siết cơ, cutting, tốt cho tim mạch. Phòng chống các bệnh về tim mạch. ?? 5 vị thơm ngon. Ướp được các món dành cho fitness cực đã, mà không mất quá nhiều công chế biến như: ức gà - thịt bò - cá hồi....Kết hợp CHIÊN_ XÀO_NẤU_ NƯỚNG_ÁP CHẢO cùng Dầu ăn dạng xịt O Calo nữa là chuẩn không cần chỉnh. ?? ‼️Giá:209k/ hũ(156gram)xài hơn 22lần ướp. heathy shop có tách nhỏ gói 10g mỗi vị 1 gói để cho khách hàng test thử. Combo 5 gói 50g chỉ 150k\r\n', 'giavi1.jpg', 'giavi2.jpg'),
(43, 'Đường ăn kiêng', 25, 'Gói', 198000, 5, 'JC BLUEMOON Co.LT\r\n\r\nNhãn hiệu đường tự nhiên không năng lượng đầu tiên của Việt Nam\r\n\r\nSản phẩm: Đường La Hán Quả | Đường Erythritol | Đường Cỏ Ngọt Stevia\r\n\r\nSản phẩm JC BLUEMOON Erythritol là một sản phẩm làm ngọt thay thế đường tuyệt vời vì:\r\n\r\n- Non-GMO, hoàn toàn tự nhiên, độ ngọt 70% đường mía.\r\n\r\n- Không làm tăng chỉ số đường huyết (Glycemic Index, GI=0)\r\n\r\n- Thích hợp cho những người theo chế độ ăn kiêng, Keto, tiểu đường, eatclean.\r\n\r\n- Không gây sâu răng\r\n\r\n-Khối lượng tịnh 500g - Hãng: JC BLUEMOON', 'duong1.jpg', 'duong2.jpg'),
(44, 'Dầu ăn kiêng PAM dạng xịt', 34, 'Chai', 215000, 5, 'Non-Stick Pam Cooking Spray Original 10 oz ( Khoảng hơn 1000 lần xịt )\r\n1 Trong Những Thương Hiệu Lâu Năm Của Mỹ Về Dòng Sản Phẩm Cooking Spray - Dầu Ăn Kiêng Số 1 Tại Mỹ\r\nTha Hồ Chiên - Xào Thoải Mái Mà Không Lo Tăng cân.\r\nThay Vì Sử Dụng Dầu Ăn Thường ( 1 Muỗng 14gram = 150 kcal ~ 30 phút Chạy Bộ ) Tại sao Không Dùng Thử Sản Phẩm Dầu Ăn Cooking Spray 0kcal . Không Làm Tăng Cân Và Không Làm Mất Thêm Thời Gian Luyện Tập.\r\nxuất xứ : Tại USA ( Mỹ )\r\nThích Hợp :\r\nCho Người Ăn Kiêng Có Thể Ăn Đồ Chiên Xào Mà Không Lo Uổng Công Giảm Cân .\r\nDân Tập Gym Hay Xài Do Lợi Ích Của Nó :\r\n. 0 kcal.\r\n. 0 cholesterol\r\n. 0 sodium\r\n. 0 trans fat\r\nDễ Dàng Chùi Rửa , Không Dính Chảo\r\n100% Hàng USA . Phát Hiện Hàng Giả Hoàn Trả 200% ..\r\nDân gym Sử Dụng Dầu Ăn Này Có Thể Ăn Chiên Xào Thoải Mái .', 'dau1.jpg', 'dau2.jpg');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `tbl_san_pham`
--
ALTER TABLE `tbl_san_pham`
  ADD PRIMARY KEY (`sp_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `tbl_san_pham`
--
ALTER TABLE `tbl_san_pham`
  MODIFY `sp_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=45;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
